### ISSUE TITLE
Alter unique, nullable field to non-unique, nullable fails

### ISSUE THREAD

**Issue by rubendv** [microsoft/mssql-django#100]
When a field is nullable and unique, a filtered index is created to enforce uniqueness instead of a unique constraint.
But when the field is made non-unique and still nullable, the generated SQL uses DROP CONSTRAINT instead of DROP INDEX, which doesn't work.

In our case this happened when changing this model:

```python
class MyModel(models.Model):
    field1= models.CharField(max_length=254, null=True, unique=True)
    field2 = models.ForeignKey('myapp.othermodel', null=False, on_delete=models.deletion.CASCADE)
```

To this model:
```python
class MyModel(models.Model):
    field1= models.CharField(max_length=254, null=True)
    field2 = models.ForeignKey('myapp.othermodel', null=False, on_delete=models.deletion.CASCADE)

    class Meta:
        unique_together = ('field2', 'field1')
```

Probably also happens without the unique_together but by just setting unique=False.

**Comment by rubendv** [comment]
This commit fixes the immediate issue for us, but is probably incomplete: https://github.com/Awingu/mssql-django/commit/6ff4298ca22f1bd0436b9f1ce6dbe9ace8ea1bc0

**Comment by absci** [comment]
Hi, I couldn't reproduce this. Is it also migrated with `django-pyodbc-azure` before like you mentioned in #104? 
We'll investigate this issue, it's better to have a fix anyway for people switched to `mssql-django`.

**Comment by rubendv** [comment]
Yes you’re probably right. In the meantime I’ve noticed that django-pyodbc-azure uses unique constraints whenever possible (not null) while mssql-django seems to always use unique indexes even if all columns are not null, and that is what is causing these issues.
