### ISSUE TITLE
Removing unique together constraint created by django-pyodbc-azure fails

### ISSUE THREAD

**Issue by rubendv** [microsoft/mssql-django#104]
When removing a unique together constraint, the generated SQL uses DROP INDEX, which produces the following error:

`django.db.utils.ProgrammingError: ('42000', "[42000] [FreeTDS][SQL Server]An explicit DROP INDEX is not allowed on index 'mymodel_field1_field2_uniq'. It is being used for UNIQUE KEY constraint enforcement. (3723) (SQLExecDirectW)")`

If it uses `ALTER TABLE <table> DROP CONSTRAINT mymodel_field1_field2_uniq` instead, it works fine.
~~See this commit for a solution that solved the issue for us: https://github.com/Awingu/mssql-django/commit/2a7d24532ac49f56bf55bedf6e48a0d36a4fb427~~ Flawed solution, see below.

**Comment by rubendv** [comment]
I sketched out a more complete solution here: https://github.com/Awingu/mssql-django/commit/7c91d3bebfa089fe6c348e62c07dc71f7f353bef, I still need to test this and I will make a PR when it seems ok.

**Comment by absci** [comment]
It makes sense to detect whether it's an index or constraint to drop. Feel free to make a PR when you're ready.
