### ISSUE TITLE
The data types nvarchar(max) and ntext are incompatible in the equal to operator

### ISSUE THREAD

**Issue by anrub** [microsoft/mssql-django#118]
I am using the acme2certifier project with mssql-django database backend, and there is the following error thrown:

```
[42000] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]The data types nvarchar(max) and ntext are incompatible in the equal to operator. (402) (SQLExecDirectW)'
```

The columns in the table are all `varchar(max)`, so I was wondering from where the ntext may come into play?

**Comment by absci** [comment]
That's weird, this backend doesn't use `ntext`. I'm not sure how the acme2certifier project works, do you have some sample code to reproduce this error?
