### ISSUE TITLE
Limit/Offset clause didnot consider old version of sql server like 2008 in v1.1.3

### ISSUE THREAD

**Issue by Pandaaaa906** [microsoft/mssql-django#125]
might related by [#117](https://github.com/microsoft/mssql-django/pull/117)

**Comment by jmah8** [comment]
Thanks for the report, we are discussing this internally.

**Comment by jmah8** [comment]
SQL Server 2008 is no longer supported. OFFSET was added in SQL Server 2012. Could you update to a newer supported version of SQL Server?

**Comment by jmah8** [comment]
I am going to close this issue as SQL Server 2008 is unsupported. Feel free to open a new issue if you are encountering the same issue with newer versions of SQL Server.

**Comment by jmah8** [comment]
Unfortunately, since SQL Server 2008 is end of life we cannot install it for testing purposes without it getting flagged as a security concern. Since we do not want to add code that can't be tested, we aren't planning to make any changes that affect only SQL Server 2008.

**Comment by Pandaaaa906** [comment]
@Alukardz you could just use an older version, it kinda ok
