### ISSUE TITLE
Django ORM returns non-iterable object

### ISSUE THREAD

**Issue by debadatta-tiger-analytics** [microsoft/mssql-django#127]
The model is-
class WeeklyStrMst(BaseModel):
    StoreId = models.AutoField(primary_key=True)
    TDLinx_No = models.IntegerField(blank=True, null=True, default=None)
    Week = models.IntegerField(blank=True, null=True, default=None)
    Week_Number = models.IntegerField(blank=True, null=True, default=None)
    Year = models.IntegerField(blank=True, null=True, default=None)
    Category = models.CharField(max_length=75, blank=True, null=True, default=None)
    SeasonalPackaging = models.CharField(max_length=75, blank=True, null=True, default=None)
    Consumption = models.CharField(max_length=75, blank=True, null=True, default=None)
    Manufacturer = models.CharField(max_length=75, blank=True, null=True, default=None)
    PackType = models.CharField(max_length=75, blank=True, null=True, default=None)
    Volume = models.FloatField(blank=True, null=True, default=None)
    POS = models.FloatField(blank=True, null=True, default=None)
    StoreName = models.CharField(max_length=75, blank=True, null=True, default=None)
    MasterChain = models.CharField(max_length=75, blank=True, null=True, default=None)
    TerritoryName = models.CharField(max_length=75, blank=True, null=True, default=None)
    RegionName = models.CharField(max_length=75, blank=True, null=True, default=None)
    StoreClassification = models.CharField(max_length=75, blank=True, null=True, default=None)
    StateName = models.CharField(max_length=75, blank=True, null=True, default=None)
    class Meta:
        managed = True
        db_table = config_data[settings.REGION_NAME]['tables']['weekly_mstr']
        
        
Now, I query the data
`WeeklyStrMst.objects.filter(StoreId__in=stores).values('TDLinx_No')`
 
 Here stores is of list datatype containing 6000-30000 values which are non-null, integer, so when I execute this, it returns me -

`<django.db.models.query.QuerySet object at 0x0000024FD4EAAAF0>`

I have tested with less than 2000 values it works fine. What could be possible reason and workaround for this scenario? How to pass a large list of values as a filter criteria?

**Comment by timnyborg** [comment]
The reason will be a hard technical limitation in MSSQL - you cannot excede 2100 parameters in a query, so trying to supply a list of 6000+ will fail, whether you're using Django or running SQL directly against the database.

You should be using a Subquery if at all possible.  See https://docs.djangoproject.com/en/4.0/ref/models/expressions/#subquery-expressions

**Comment by debadatta-tiger-analytics** [comment]
@timnyborg we have converted to raw sql queries and its taking 25k values in list at a time. In your opinion which is the optimal way with respect to performance, Django queryset(2100 values only as parameter) or raw sql query?

**Comment by debadatta-tiger-analytics** [comment]
@timnyborg which db allows us to pass maximum values as a list? That will be great help.

**Comment by debadatta-tiger-analytics** [comment]
Is there any way to override this feature? @timnyborg

**Comment by jmah8** [comment]
timnyborg is correct, MSSQL has a max of 2100 parameters. We will investigate the performance of using Django compared to raw sql and overriding the 2100 limit.

**Comment by jmah8** [comment]
@debadatta-tiger-analytics I could not reproduce this using version 1.1.3. If you haven't already could you check to see if the latest version fixes it?

**Comment by debadatta-tiger-analytics** [comment]
@jmah8 django.VERSION is (3, 1, 2, 'final', 0). Were you able to pass more than 2100 values in an array as param?

**Comment by debadatta-tiger-analytics** [comment]
@jmah8 I have updated the version, let me check. Interesting.

**Comment by debadatta-tiger-analytics** [comment]
@jmah8 its working after the update, thank you.
