### ISSUE TITLE
API Working on local but not on App Service Deployment [Django]

### ISSUE THREAD

**Issue by 9Shuck** [microsoft/mssql-django#132]
Hi! I've coded an API with Django Rest Framework that is connected to an azure DB.

The thing is that everything is working fine locally but when I deploy the app to App Service the endpoints that access the DB don't work. If I create a simple endpoint that returns 'Hello world' and it doesn't need to access the DB it works, but when I try to login it doesn't work.

I'm receiving this error: **('01000', "[01000] [unixODBC][Driver Manager]Can't open lib 'ODBC Driver 18 for SQL Server' : file not found (0) (SQLDriverConnect)")**

I've tried a lot of things but anything works. Thank you so much in advance.

**Comment by 9Shuck** [comment]
> This error is usually from not having the specified ODBC Driver installed.

Sorry but where should I install it? I took a look into it and I cannot install ODBC Driver inside App Service. But I have everything inside the requirements.txt and the app works if I not access to the DB. There are any logs I can share to make your help easier?

Thank you so much!

**Comment by jmah8** [comment]
No problem. I am closing this issue but feel free to reopen this issue if you are still having similar issues or making a new issue if you are having other issues.
