### ISSUE TITLE
Datetimeoffset support ?

### ISSUE THREAD

**Issue by 3skr0** [microsoft/mssql-django#136]
Accessing a model in the admin page that has a field mapped as datetimeoffset gives :

"ODBC SQL type -155 is not yet supported"

While using freetds driver.

I m trying odbc driver 17/18

**Comment by 3skr0** [comment]
I did a quick patch that seems to work at least by READ

in base.py adding:

```python
from datetime import datetime, timedelta, timezone
import struct

def handle_datetimeoffset(dto_value):
    tup = struct.unpack("<6hI2h", dto_value)
    return datetime(tup[0], tup[1], tup[2], tup[3], tup[4], tup[5], tup[6] // 1000,
                    timezone(timedelta(hours=tup[7], minutes=tup[8])))
```
then in get_new_connection() method, before the return adding:
```python
cnxn.add_output_converter(-155, handle_datetimeoffset)
```

**Comment by jmah8** [comment]
You are correct for using an output converter function for adding support for datetimeoffset. We are also planning on adding support for this in the next release.

**Comment by jmah8** [comment]
Closing this issue as support for datetimeoffset has been added in PR #140 and will be included in the next release.
