### ISSUE TITLE
Not working with MSSQL on Linux

### ISSUE THREAD

**Issue by vindevoy** [microsoft/mssql-django#149]
I'm running on Mint on my desktop and for local development, I installed MSSQL.  

I can connect to the database using e.g. DataGrid from Jetbrains.  The version using SELECT @@VERSION is 

```
Microsoft SQL Server 2022 (CTP2.0) - 16.0.600.9 (X64) 
	May 20 2022 13:29:42 
	Copyright (C) 2022 Microsoft Corporation
	Developer Edition (64-bit) on Linux (Linux Mint 20.3) <X64>
```

I'm using Poetry for my dependencies.  The versions installed are:

```
[tool.poetry.dependencies]
python = "^3.10"
Django = "^4.0.5"
mssql-django = "^1.1.3"
```

I am trying to connect Django to this server.  As Microsoft details on the website: 

https://docs.microsoft.com/en-us/samples/azure-samples/mssql-django-samples/mssql-django-samples/

I'm using mssql-django to connect and my settings.py contains this:

```
"default": {
        "ENGINE": "mssql",
        "NAME": "*********",
        "USER": "****",
        "PASSWORD": "****",
        "HOST": "localhost",
        "PORT": "1433",
        "OPTIONS": {
            "Encrypt": "no",
            "driver": "ODBC Driver 17 for SQL Server"
        },
    },
```

I have already lost a lot of time on the encrypt = no stuff.  I always had the SSL verification error on the self signed certificate.  This is poorly documented on the site.  Now this is fixed, I end up with this error:

**django.db.utils.NotSupportedError: SQL Server v16 is not supported.**

The stacktrace clearly shows why:

```
    if self.sql_server_version <= 2005:
  File "/home/vindevoy/.cache/pypoetry/virtualenvs/sofort-n7HBP2PA-py3.10/lib/python3.10/site-packages/django/utils/functional.py", line 49, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/vindevoy/.cache/pypoetry/virtualenvs/sofort-n7HBP2PA-py3.10/lib/python3.10/site-packages/mssql/base.py", line 450, in sql_server_version
    raise NotSupportedError('SQL Server v%d is not supported.' % ver)
```

Apparently the version number on Linux, which is not year related, is causing this problem:

**if self.sql_server_version <= 2005:**

**Comment by jmah8** [comment]
This is because we don't currently support  SQL Server 2022, but are planning to. Using an older supported version of SQL Server like 2019 should work and not throw that unsupported version error.

**Comment by epomatti** [comment]
@jmah8 thanks for the tip.

Will this imply any compatibility issues with Azure SQL Database?
Also, any roadmap for version 2022 support?

**Comment by vindevoy** [comment]
Installing an older version of SQL Server does not work as smoothly as expected.

- With the normal repo file, you can only install the latest version, which is 16 or 2022, however you call it.  It would be nice if you could say "apt install mssql-server-2019" 
- I downloaded it manually as a .deb package.  After installing the server did not run because the daemon was crashing.  I manually removed folders in /var/lib/mssql, /opt/microsoft, /opt/mssql, ...  Now it works finally.  
- I ended up doing the same with the mssql-tools package. 
- The configuration of Django is fairly simple, and is according to the documentation, but, the creation of the database is not as simple.  I don't want the default settings like a schema in the master database.  Nor do I want to change settings in Django, as I want to support other databases also.  I spent a whole afternoon on this as the documentation is not mentioning this at all.  I ended up with the script below.

`
USE master
GO

CREATE LOGIN sofort
    WITH PASSWORD='*****'
GO

CREATE DATABASE sofort
GO

USE sofort
GO

CREATE USER sofort
    FOR LOGIN sofort
GO

CREATE SCHEMA sofort_dev
GO

ALTER USER sofort
    WITH DEFAULT_SCHEMA = sofort_dev
GO

GRANT ALTER, CONTROL, REFERENCES
    ON DATABASE ::sofort TO sofort
GO

GRANT ALTER, CONTROL, CREATE SEQUENCE, DELETE, INSERT, REFERENCES, SELECT, UPDATE
    ON SCHEMA ::sofort_dev TO sofort
GO

USE master
GO
`

**Comment by jmah8** [comment]
@epomatti Azure SQL Database usually doesn't have issues when it is updated. Unfortunately there is no roadmap for SQL Server 2022 support yet but we are planning on supporting it.

@vindevoy Thank you for taking the time to detail the steps you took. This will be helpful for others in a similar situation.

**Comment by jmah8** [comment]
I'm going to close this issue now but feel free to reopen it if you are still having issues.

**Comment by shakthifuture** [comment]
Why new version v16 not supported?
