### ISSUE TITLE
License changed from BSD to MIT without permission

### ISSUE THREAD

**Issue by sparrowt** [microsoft/mssql-django#15]
Filing this as a separate issue so it doesn't get lost in a comment thread on the repo from which this was forked:
https://github.com/ESSolutions/django-mssql-backend/issues/91#issuecomment-799382717

> I noticed the license of the fork [has been changed](https://github.com/microsoft/mssql-django/commit/6539d7101aa72f9ea6c7b746d11c98b190d57698#diff-c693279643b8cd5d248172d9c22cb7cf4ed163a3c98c8a3f69c2717edd3eacb7) from BSD 3-Clause to MIT - may I ask from whom you obtained [permission](https://opensource.stackexchange.com/questions/5710/is-it-possible-to-move-from-bsd-to-mit-without-author-consent) to alter the license?
>
> History of LICENSE through chain of forks (BSD, with varying authors): [django-pyodbc](https://github.com/avidal/django-pyodbc/blob/django-1.4/LICENSE), [django-pyodbc-azure](https://github.com/michiya/django-pyodbc-azure/blob/azure-2.1/LICENSE), [django-mssql-backend](https://github.com/ESSolutions/django-mssql-backend/blob/master/LICENSE)

Thank you @vwarchu for the response:

> @sparrowt - thanks for pointing this out, we'll put this through a legal review process to evaluate reverting to the BSD 3-Clause.

I trust this ticket can serve to track resolving this issue.

As well as re-instating the license it would be appropriate (if not required - I'll let you talk to the lawyers!) to retain the Copyright lines from each fork in the chain, especially the original "django-pyodbc developers" one, to acknowledge their contributions over many years - rather than just _replacing_ them all with "Copyright (c) Microsoft Corporation" on its own which I believe is incorrect.

**Comment by vwarchu** [comment]
@sparrowt - Yes, tracking this issue here is recommended. Thanks

**Comment by sparrowt** [comment]
I noticed that LICENSE.txt has now been reverted to BSD 3-Clause by https://github.com/microsoft/mssql-django/commit/4dfb39c028dcdf3a1d6f5f5f10bc3404a333fdde, thank you!

For some reason GitHub isn't displaying the license 'infobox' at the top of https://github.com/microsoft/mssql-django/blob/dev/LICENSE.txt (whereas for example [the parent of this fork](https://github.com/ESSolutions/django-mssql-backend/blob/master/LICENSE) does) - see [here](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/licensing-a-repository#detecting-a-license) re auto-detection - possibly due to this extra line at the top:
> Project Name: mssql-django

**Comment by sparrowt** [comment]
The other thing mentioned in the description of this issue is the copyright notice - unfortunately this still says simply:
>  Copyright (c) Microsoft Corporation

which doesn't acknowledge the years of work by the following (from previous license files linked above):
> django-pyodbc developers

> Michiya Takahashi

> ES Solutions AB

though I realise this may be more of a grey area, but I thought I'd point it out.

**Comment by vwarchu** [comment]
@sparrowt - Thanks for your patience - I've now updated the License.txt file in the dev branch to account for the historical copyright notices. This will be merged this week and be part of the subsequent releases.

**Comment by sparrowt** [comment]
Thank you @vwarchu. 10f05255159a029e45c0dc1ae51de24da8c051da for the interested. Also related: aca9d268987076d7c257580ffb501e176c0c0178 👍
