### ISSUE TITLE
Connecting from Linux Server Using Service Account 

### ISSUE THREAD

**Issue by djogo16** [microsoft/mssql-django#151]
Is there a way to configure connection to SQL Server using non-Azure LDAP accounts? I have a service account that is part of a LDAP group and tried the connection details below,  inspired by https://github.com/microsoft/mssql-django/wiki/Azure-AD-Authentication

DATABASES = {
	    "default": {
	        "ENGINE": "mssql",
	        "NAME": "default",
	        "USER": serviceAccountID
	        "PASSWORD": serviceAccountPassword,
	        "HOST": "example.database.windows.net",
	        "PORT": "1433",
	        "OPTIONS": {
	            "driver": "ODBC Driver 17 for SQL Server",
	            "extra_params": "Authentication=ActiveDirectoryServicePrincipal",
	        },
	    },
	}

Getting this error:

django.db.utils.OperationalError: ('08001', "[08001] [Microsoft] [ODBC Driver 17 for SQL Server] Invalid value specified for connection string attribute 'Authentication' (0) (SQLDriverConnect) ")

**Comment by jmah8** [comment]
Hi, I was wondering what you mean when you say "non-Azure LDAP account". Is it regular Active Directory, Kerberos, or something else? Could I also get some more information about your setup to know what you are trying to do?

**Comment by djogo16** [comment]
Hi, by non-Azure LDAP group I meant a regular Active Directory on Windows.  We have regular windows AD for users and service accounts. We created a service account ID and password, added to an existing AD group on windows. Now we're trying to use that service account to authenticate to a mssql server database that our django application uses.

My setup:

Django 3.2 running on RHEL 7.9.
Trying to use mssql  server as the database

**Comment by jmah8** [comment]
I am going to close this issue but feel free to reopen it if you are still having issues.
