### ISSUE TITLE
Incorrect query on SQL Server 2008 R2 (OFFSET clause)

### ISSUE THREAD

**Issue by nchurkin** [microsoft/mssql-django#154]
I'm trying to use Django with old system using MS SQL 2008 R2. I'm using ODBC Driver 17 for SQL Server for mssq-django (1.1.3).

When I making first migration before describing models I have an error:
`
pyodbc.ProgrammingError: ('42000', "[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Incorrect syntax near 'OFFSET'. (102) (SQLExecDirectW); [42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Statement(s) could not be prepared. (8180)")
`

I see that query is incorrect, SQL SERVER 2008 R2 doesn't support OFFSET clause :
`SELECT [auth_permission].[content_type_id], [auth_permission].[codename] FROM [auth_permission] INNER JOIN [django_content_type] ON ([auth_permission].[content_type_id] = [django_content_type].[id]) WHERE [auth_permission].[content_type_id] IN (?) ORDER BY [django_content_type].[app_label] ASC, [django_content_type].[model] ASC, [auth_permission].[codename] ASC OFFSET 0 ROWS (1,)
`

I printed some variables from compiler.py:
```
sql_server_version=2008
do_offset=False
do_limit=False
supports_offset_clause=False
do_offset_emulation=False
```

But I see that this condition is True and "OFFSET 0 ROWS" appends to query:
```
                # For subqueres with an ORDER BY clause, SQL Server also
                # requires a TOP or OFFSET clause which is not generated for
                # Django 2.x.  See https://github.com/microsoft/mssql-django/issues/12
                # Add OFFSET for all Django versions.
                # https://github.com/microsoft/mssql-django/issues/109
                if not (do_offset or do_limit):
                    result.append("OFFSET 0 ROWS")
```

Maybe condtion should be like this?
```
 if supports_offset_clause and not (do_offset or do_limit):
                    result.append("OFFSET 0 ROWS")
```

**Comment by jmah8** [comment]
SQL Server 2008 is end of life and no longer supported by us. Since OFFSET was added in 2012 could you update to a newer version of SQL Server? If not you could try downgrading mssql-django as another user had the same issue as you and said it is kind of ok.

**Comment by jmah8** [comment]
I am going to close this issue now but feel free to open a new issue if you are having other issues.
