### ISSUE TITLE
Model.objects.bulk_create() does not return PK's

### ISSUE THREAD

**Issue by paxw-panevo** [microsoft/mssql-django#155]
In the [django docs](https://docs.djangoproject.com/en/3.0/ref/models/querysets/#bulk-create) for bulk_create(),

> If the model’s primary key is an [AutoField](https://docs.djangoproject.com/en/3.0/ref/models/fields/#django.db.models.AutoField) it does not retrieve and set the primary key attribute, as save() does, unless the database backend supports it (currently PostgreSQL).

Can the mssql database backend support this?

**Comment by jmah8** [comment]
Yes, the mssql backend does retrieve and set the primary key when using bulk_create() in version 1.1.3
