### ISSUE TITLE
unicode_results Invalid connection string attribute login timeout

### ISSUE THREAD

**Issue by powelleric** [microsoft/mssql-django#159]
I am experiencing login timeouts occasionally.  I did an ODBC trace and got: 

```
[ODBC][93319][1658948833.081712][SQLDriverConnect.c][748]
                Entry:
                        Connection = 0x7fcea7315a00
                        Window Hdl = 0x0
                        Str In = [DRIVER=ODBC Driver 17 for SQL Server;SERVER=localhost;UID=develop;PWD=*************;DATABASE=mydevdb;unicode_results=False;][length = 123 (SQL_
NTS)]
                        Str Out = 0x7ff7ba7d9600
                        Str Out Max = 2048
                        Str Out Ptr = 0x0
                        Completion = 0
                DIAG [08001] [Microsoft][ODBC Driver 17 for SQL Server]TCP Provider: Error code 0x2726

                DIAG [HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired

                DIAG [01S00] [Microsoft][ODBC Driver 17 for SQL Server]Invalid connection string attribute

                DIAG [08001] [Microsoft][ODBC Driver 17 for SQL Server]A network-related or instance-specific error has occurred while establishing a connection to SQL Server. Server is not found or not accessible. Check if instance name is correct and if SQL Server is configured to allow remote connections. For more information see SQL Server Books Online.
```

I checked and I can't find any documentation about `unicode_results` as a connection string parameter.

**Comment by jmah8** [comment]
unicode_results is not from the ODBC driver but from pyodbc which we use in this project. The default is `False` so it appearing in the connection string is expected. For example here is an ODBC trace from my machine: 
```
[ODBC][8513][1658964080.812793][SQLDriverConnectW.c][290]
		Entry:
			Connection = 0x1b8d3c0
			Window Hdl = (nil)
			Str In = [DRIVER=ODBC Driver 17 for SQL Server;SERVER=XXX.XXX.XXX.XXX,1433;UID=******;PWD=******;DATABASE=default;unicode_results=False;][length = 125 (SQL_NTS)]
			Str Out = (nil)
			Str Out Max = 0
			Str Out Ptr = (nil)
			Completion = 0
		UNICODE Using encoding ASCII 'UTF-8' and UNICODE 'UTF-16LE'

```
and I am not getting the same errors as you. This may be an issue with your setup. What version of SQL Server and pyodbc are you using?

**Comment by powelleric** [comment]
> unicode_results is not from the ODBC driver but from pyodbc which we use in this project. 

I'm a bit confused, then.  Are you saying this module isn't responsible for adding it to the connection string? Seems like it is added to the connection string by this module around this line: https://github.com/microsoft/mssql-django/blob/e2fd494ae9537f98a905f8de7a15930e391246c6/mssql/base.py#L340

Can you link me to any documentation showing that unicode_results is a valid parameter for the connection string?
 
> and I am not getting the same errors as you. This may be an issue with your setup.

OK I will look elsewhere.

**Comment by jmah8** [comment]
FYI if you are using SQL Server 14 it may be because SQL Server 14 uses an out-dated SSL version [source](https://github.com/r-dbi/odbc/issues/460). Also pyodbc 4.0.34 is broken and while I don't see people using 4.0.34 having the same issue as you, maybe downgrading to 4.0.32 could help.

I am more than happy to try to reproduce this and help you solve this issue if you want.
