### ISSUE TITLE
Django 4.1 support?

### ISSUE THREAD

**Issue by Jamztown** [microsoft/mssql-django#162]
Are there any plans to update this package to utilize Django 4.1 that just came out? Doing some extremely basic testing I got it to function by messing with the install order and changing just a couple of lines. But more testing is definitely required to see if any real updates are needed to this package to keep it compatible with 4.1

**Comment by jmah8** [comment]
Yes there are plans to support Django 4.1. We are currently doing some testing to see what needs to be updated to support Django 4.1.

**Comment by patrickfish** [comment]
Looks like there were some breaking changes in many of the date/time DatabaseOperations methods in Django 4.1. QuerySet filters using `__date=datetime.now()` throw a `DatabaseOperations.datetime_cast_date_sql() takes 3 positional arguments but 4 were given` error.

**Comment by jmah8** [comment]
Yes we are aware of the breaking changes to the date/time DatabaseOperations. We are changing all the methods listed in the backwards incompatible changes in the [Django 4.1 docs](https://docs.djangoproject.com/en/4.1/releases/4.1/#backwards-incompatible-changes-in-4-1) but there are still other unit test failing which we are working through.

**Comment by iamjameswalters** [comment]
Curious to know if there's an update on this front? Currently developing against 4.0 and would love to move to 4.1 as soon as the dust settles here. 

Thanks to everyone working on this--much appreciated!

**Comment by mShan0** [comment]
Currently, we're targeting December for Django 4.1 support

**Comment by jnovinger** [comment]
@jmah8 , is there any update on whether Django 4.1 support will still be ready for release in December?

Is there anywhere the community can help with this? Is there a punch list of items left to complete for the release somewhere?

 I didn't see anything other than the [December release](https://github.com/microsoft/mssql-django/wiki/Upcoming-Release-Notes#december-release) notes in the wiki and the the [django41](https://github.com/microsoft/mssql-django/tree/django41) branch.

**Comment by mShan0** [comment]
Hi @jnovinger, our release for Django 4.1 support will be on Dec 8. We just have a few more unit tests from the Django library to resolve.

**Comment by mShan0** [comment]
Support for Django 4.1 has been released with `mssql-django 1.2`
