### ISSUE TITLE
Cannot deploy to Azure App Service Linux (Can't open lib 'ODBC Driver 17 for SQL Server' : file not found)

### ISSUE THREAD

**Issue by TCFox** [microsoft/mssql-django#167]
Adding this here hoping that it'll save someone else a world of pain, but would love if there was any additional ideas or comments on how to resolve this.

Currently I'm no longer unable to deploy my Django (4.0.x) app to Azure App Service Linux (through GitHub Actions), despite having `pyodbc`, `pytz` and `mssql-django` defined in my `requirements.txt`. I get the following error:
```
Traceback (most recent call last):
  File "/tmp/8da818f72fca2a0/antenv/lib/python3.9/site-packages/django/db/backends/base/base.py", line 244, in ensure_connection
    self.connect()
  File "/tmp/8da818f72fca2a0/antenv/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/tmp/8da818f72fca2a0/antenv/lib/python3.9/site-packages/django/db/backends/base/base.py", line 225, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/tmp/8da818f72fca2a0/antenv/lib/python3.9/site-packages/mssql/base.py", line 353, in get_new_connection
    conn = Database.connect(connstr, **args)
pyodbc.Error: ('01000', "[01000] [unixODBC][Driver Manager]Can't open lib 'ODBC Driver 17 for SQL Server' : file not found (0) (SQLDriverConnect)")
```

It appears there may be an issue with Azure App Service Linux itself, [according to this comment](https://docs.microsoft.com/en-us/answers/questions/962107/critical-outage-app-service-not-finding-odbc-drive.html):
> I have been informed by Azure support that the problem is a known platform issue that came up after the Antares 99 upgrade. They're working on a solution but as a (temporary) they suggest adding a startup script with
> ```bash
> #!/bin/bash
> apt-get update
> apt-get install -y unixodbc-dev
> ACCEPT_EULA=Y apt-get install msodbcsql17
> <startup command to launch your application>
> ```
> This has got the application up and running again.

I'm not familiar enough with App Service to understand where this "startup script" goes, but that's outside the scope of this project.

If anyone has any knowledge of a possible workaround that will get `mssql-django` working again on Azure App Service Linux given the above issues, I'm really keen to hear it! Happy to supply any additional logs as desired.

**Comment by jmah8** [comment]
I'm pretty sure the app service doesn't come with the ODBC driver anymore, so to fix it you would need to install the ODBC driver which is what the startup script does. Some information about setting up a startup script can be found in the [Microsoft docs](https://docs.microsoft.com/en-us/azure/developer/python/configure-python-web-app-on-app-service). If this doesn't fix the issue you are having, I can try looking for other ways to solve it.

**Comment by TCFox** [comment]
I'll give this a go later this week, if I have any success I'll let you know! It's difficult to know exactly what would be considered "out-of-scope" for documentation in this case, but it might be good to add this into the `readme.md` if folks here were happy with it :)

**Comment by PMCS64** [comment]
If you wish to run locally your Django app, you can simply [download on your machine](https://learn.microsoft.com/en-us/sql/connect/odbc/download-odbc-driver-for-sql-server?view=sql-server-ver16) the ODBC Driver (please download the correct version as mentioned in the database settings in your settings.py file). With Python 3.10 and up, it is recommended to use ODBC Driver **18** and not 17.

In a development configuration, make sure to download it, for example in your Dockerfile with ODBC Driver 18 (note msodbcsql18):

```dockerfile
FROM python:3.10-slim-buster
ENV PYTHONUNBUFFERED=1

RUN apt-get update -y && apt-get install -y curl gnupg && apt-get install -y --no-install-recommends apt-utils
RUN curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
RUN curl https://packages.microsoft.com/config/debian/11/prod.list > /etc/apt/sources.list.d/mssql-release.list
RUN apt-get update -y && ACCEPT_EULA=Y apt-get -y install mssql-tools msodbcsql18
COPY requirements.txt /code
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt
COPY . /code
```

Your database setting should then be:

```python
DATABASES = {
   "default": {
       "ENGINE": "mssql",
       "NAME": "<database name in Azure>",
       "HOST": "<database host in Azure>",
       "USER": "<database user username>",
       "PASSWORD": "<database user password>",
       "PORT": 1433,
       "OPTIONS": {
           "driver": "ODBC Driver 18 for SQL Server",
           "host_is_server": True,
           "extra_params": "Persist Security Info=no;MultipleActiveResultSets=no;Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;"
       },
   },
}
```

This issue should be mark as closed.
