### ISSUE TITLE
Is it possible to connect Django to SQL Server with "Windows authentication mode" using mssql-django?

### ISSUE THREAD

**Issue by hyperkai** [microsoft/mssql-django#168]
With the code below in `settings.py`, I could connect Django to SQL Server with **"Mixed mode(SQL Server Authentication mode)"** using **mssql-django**  but I couldn't with **"Windows authentication mode"**.

```python
# "settings.py"

DATABASES = {
    'default':{
        'ENGINE':'mssql',
        'NAME':'test',
        'USER':'admin',
        'PASSWORD':'admin',
        'PORT':'1433',
        'HOST':'DESKTOP-OVPAPTY\SQLEXPRESS',
       
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
        },
    }
}
```

So, is it possible to connect Django to SQL Server with "Windows authentication mode" using **mssql-django**?

**Comment by jmah8** [comment]
Yes this should be possible. If you are on Windows and remove the `USER` and `PASSWORD` you should be able to connect Django to SQL Server with Windows authentication mode.

**Comment by hyperkai** [comment]
Finally, by removing **USER**, **PASSWORD** and **PORT**, I could connect Django to SQL Server with "Windows authentication mode" using mssql-django. Thanks.

DATABASES = {
    'default':{
        'ENGINE':'mssql',
        'NAME':'test',
        # 'USER':'admin',
        # 'PASSWORD':'admin',
        # 'PORT':'1433',
        'HOST':'DESKTOP-OVPAPTY\SQLEXPRESS',
       
    
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
        },
    }
}

**Comment by jmah8** [comment]
No problem. Closing this issue now.
