### ISSUE TITLE
New release underway ?

### ISSUE THREAD

**Issue by lendenmc** [microsoft/mssql-django#173]
Hello,

Latest release is dated April 28th. Since then many tricky bug fixes has been merged, including  PR #163 and #128 which solve problems we are running into. 

Are you closing in on a new release ?

That would be greatly appreciated.

Thanks for all the work on the new commits so far.

**Comment by mShan0** [comment]
Hi @lendenmc, our next release is scheduled to be released in early December. This will include all of the current bug fixes and future ones also.

**Comment by mShan0** [comment]
Hi @lendenmc, We just released our new version `1.2`!
