### ISSUE TITLE
``--natural-foreign`` raises CommandError

### ISSUE THREAD

**Issue by dakotahorstman** [microsoft/mssql-django#185]
Attempting to run ``python manage.py dumpdata`` with the ``--natrual-foreign`` switch causes SQL Server to raise

```CommandError: Unable to serialize database: ('HY000', '[HY000] [Microsoft][ODBC Driver 17 for SQL Server]Connection is busy with results for another command (0) (SQLExecDirectW)')```

My full command:
``python manage.py dumpdata --natural-foreign --exclude auth.permission --exclude contenttypes --exclude sessions.session > datadump.json``

``--natural-primary`` raises no such error and returns successfully.

My configuration:
```python
DATABASES = types.MappingProxyType(
    {
        "default": {
            "ENGINE": "mssql",
            "NAME": "aaIndustrialVision",
            "HOST": "dataprod.hostname.com",
            "USER": "IndustrialVision",
            "PASSWORD": os.environ.setdefault(
                "MSSQL_DATABASE_PASSWORD",
                _MSSQL_DATABASE_PASSWORD,
            ),
            "OPTIONS": {
                "driver": "ODBC Driver 17 for SQL Server",
            },
        },
    },
)
```

I'm no expert in natural keys but this doesn't seem like the expected behavior.

I'm currently running ``mssql`` with commit https://github.com/microsoft/mssql-django/commit/924e8ee43731d839a20a4c30899c62ecd3ee8eb8 and Django 4.0.7 installed through pip.

**Comment by mShan0** [comment]
Hi @dakotahorstman, do you have any more details/reproduction steps? I'm not running into any errors using `--natural-foreign`. 

What you could try is activating multiple active result sets like this:
```
"OPTIONS": {
    "driver": "ODBC Driver 17 for SQL Server", 
    "extra_params": "MultipleActiveResultSets=True"
},
```

**Comment by dakotahorstman** [comment]
Hi @mShan0,

Thanks for tackling this with me. I just tried your suggestion to no avail. Here is my current environment:

```shell
aioredis==1.3.1
asgiref==3.5.2
asttokens==2.0.8
async-timeout==4.0.2
attrs==22.1.0
autobahn==22.7.1
Automat==20.2.0
backcall==0.2.0
certifi==2022.9.14
cffi==1.15.1
channels==3.0.5
channels-redis==3.4.1
click==8.1.3
colour==0.1.5
constantly==15.1.0
crispy-bootstrap5==0.6
cryptography==38.0.1
daphne==3.0.2
decorator==5.1.1
distlib==0.3.6
Django==4.0.7
django-betterforms==2.0.0
django-chartjs==2.3.0
django-crispy-forms==1.14.0
django-polymorphic==3.1.0
executing==1.1.0
filelock==3.8.0
gunicorn==20.1.0
h11==0.14.0
hiredis==2.0.0
hyperlink==21.0.0
idna==3.4
incremental==21.3.0
ipython==8.5.0
jedi==0.18.1
loguru==0.6.0
matplotlib-inline==0.1.6
msgpack==1.0.4
mssql-django @ git+https://github.com/microsoft/mssql-django.git@924e8ee43731d839a20a4c30899c62ecd3ee8eb8
numpy==1.23.3
opencv-python==4.6.0.66
packaging==21.3
parso==0.8.3
pexpect==4.8.0
pickleshare==0.7.5
Pillow==9.2.0
platformdirs==2.5.2
pluggy==1.0.0
prompt-toolkit==3.0.31
ptyprocess==0.7.0
pure-eval==0.2.2
py==1.11.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycparser==2.21
Pygments==2.13.0
pyodbc==4.0.34
pyOpenSSL==22.1.0
pyparsing==3.0.9
pytz==2022.2.1
service-identity==21.1.0
six==1.16.0
sqlparse==0.4.3
stack-data==0.5.1
tomli==2.0.1
tox==3.26.0
tox-conda==0.9.2
traitlets==5.4.0
Twisted==22.8.0
txaio==22.2.1
typing_extensions==4.3.0
uvicorn==0.18.3
virtualenv==20.16.5
wcwidth==0.2.5
zope.interface==5.4.0
```

I am using django-polymorphic quite heavily in this project. I'm suspicious that it is causing the issue I am having. For example, many of my models look like this:

**base.py**
```python
from polymorphic import models as poly_models

class ParentModel(poly_models.PolymorphicModel):
    # Normal Django fields here (like CharField, IntegerField, etc...)
    ...

class ParentModel2(poly_models.PolymorphicModel):
    # Normal Django fields here
    ...
```

**child_a.py**
```python
from base import ParentModel, ParentModel2

class ChildAModel(ParentModel):
    # Child-specific fields here, also normal Django fields
    ...

class ChildAModel2(ParentModel2):
    # Child2-specific fields here, also normal Django fields
    ...
```

**child_b.py**
```python
from base import ParentModel, ParentModel2

class ChildBModel(ParentModel):
    # Child-specific fields here, also normal Django fields
    ...

class ChildBModel2(ParentModel2):
    # Child2-specific fields here, also normal Django fields
    ...
```

**Comment by mShan0** [comment]
Thanks for the info. I'm unfamiliar with `django-polymorphic` and `--natural-foreign` but I will attempt to find the issue. Also, looking at issue #45, it might be that our driver may not support natural keys properly yet.

**Comment by JulianOrteil** [comment]
Thank you for your willingness to help! I dont use natural keys directly, however polymorphic requires the use of ``--natural-foreign`` and ``--natural-primary`` when running ``dumpdata``. It's supposedly required for any table (model) that references ``ContentType`` objects.

I also believe my server is MSSQL 2019. I can double check on Monday though if you would like.

**Comment by mShan0** [comment]
Hi @dakotahorstman, I gave the wrong `extra_param` to activate MARS. Can you try adding `MARS_Connection=Yes` to your `extra_params`?

**Comment by dakotahorstman** [comment]
@mShan0 That did it! Is this an extra param I can leave in production or would you advise against that?

**Comment by mShan0** [comment]
I'm not 100% sure but here's a link to the Microsoft documentation on MARS:

https://learn.microsoft.com/en-us/sql/relational-databases/native-client/features/using-multiple-active-result-sets-mars?view=sql-server-ver16

Feel free to let me know if this is helpful enough or not.

**Comment by dakotahorstman** [comment]
@mShan0 I reached out to my company's internal DB admin and he said this about keeping the extra param in production:

![image](https://user-images.githubusercontent.com/112419414/203123920-6142abbe-6711-452d-9ac6-85a2a9e7fb34.png)

Django, by default, closes the connection after each request, so it shouldn't be an issue.
https://docs.djangoproject.com/en/4.1/ref/databases/#persistent-connections

I don't know if you would like to document this behavior in case someone else encounters this.
