### ISSUE TITLE
NULLS LAST added to query in django 3.1

### ISSUE THREAD

**Issue by timnyborg** [microsoft/mssql-django#19]
I'm testing upgrading from django 3.0 to 3.1, using the latest backend, version 1.0b1.  When using the `nulls_last` flag in an order_by, it appends a bit of SQL invalid in MSSQL (NULLS LAST)

The following use of nulls_last:

```python
def other_runs(self):
    return (
        Module.objects
        .filter(url=self.url, division=self.division)
        .exclude(id=self.id)
        .order_by(F('start_date').desc(nulls_last=True))
    )
```

Produces the query:
```sql
SELECT TOP 21 [module].[id], ... FROM [module] WHERE ([module].[division] = %s AND [module].[url] = %s 
AND NOT ([module].[id] = %s)) ORDER BY CASE WHEN [module].[start_date] IS NULL THEN 1 ELSE 0 END, 
[module].[start_date] DESC NULLS LAST
```

So both the MSSQL workaround and the ANSI SQL standard are there.

Naturally, this throws the error `[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Incorrect syntax near 'NULLS'. (102) (SQLExecDirectW)`

**Comment by timnyborg** [comment]
After digging into the issue, I found the backend was just missing a couple more feature flags, so I've opened pull request https://github.com/microsoft/mssql-django/pull/20

**Comment by absci** [comment]
Thanks for the pull request, we'll review it as soon as we can.

**Comment by absci** [comment]
Thank you for your contribution, this was merged.

**Comment by davidjb** [comment]
This is still an issue, but in a different way, see #31 here and I've reopened https://code.djangoproject.com/ticket/32584 and expanded the description and context.
