### ISSUE TITLE
Do we need check support for modern datatime types on every request?

### ISSUE THREAD

**Issue by GorlikItsMe** [microsoft/mssql-django#196]
https://github.com/microsoft/mssql-django/blob/fe3ee18f8ae7975bf12934796a8ddae01225a1af/mssql/base.py#L432

Do we need to on every request send `SELECT SYSDATETIME()`? Can we cache it and check only once?

**Comment by mShan0** [comment]
Hi @GorlikItsMe, we will have to look more into that. Is it causing you performance issues? Or any other issues in general?

**Comment by GorlikItsMe** [comment]
I use the `Django debug toolbar` to find what SQL query my app makes. I use 2 databases (MySQL and mssql). Some pages don't make any query to mssql database but still every request I make `SELECT SYSDATETIME()` to mssql.
Processing this query sometimes takes a long time because the database is on another server (I have high latency there) and I was wondering Is there a way to somehow disable this or make that check only before you start sending normal querys

**Comment by mShan0** [comment]
Definitely something we'll look into. Thanks for the report!

**Comment by sg3-141-592** [comment]
Hey @GorlikItsMe, looks like the fix for this just got merged. Should be caching correctly now.

**Comment by GorlikItsMe** [comment]
Yes, I can confirm the fix work. Now I'm waiting for new version release 🎉
