### ISSUE TITLE
Django MigrationSchemaMissing exception on Azure SQL using service principal auth

### ISSUE THREAD

**Issue by aashayamballi** [microsoft/mssql-django#213]
Hello all,

I'm actually working on a client's project we are connecting Azure SQL DB via service principal authentication. Our client has given us access to Azure SQL and they have given us the credential for it. so to connect to Azure SQL we're using Microsoft's mssql-django package.

so this is what the DB configurations look like.

```
DATABASES = {

    'default': {
        'ENGINE': 'mssql',
        'NAME': <db_name>,  
        'USER': <db_user>,
        'PASSWORD':<db_password>,
        'HOST': "<url>.database.windows.net",
        'PORT': '1433',
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
            'connection_timeout':60,
            'connection_retries':3,
            "extra_params": "Authentication=ActiveDirectoryServicePrincipal",
        
        },
}
```

so when I'm trying to run the migrate command I'm getting the below error

```
raise MigrationSchemaMissing(
django.db.migrations.exceptions.MigrationSchemaMissing: Unable to create the django_migrations table (('42000', '[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]The specified schema name "<db_user>@<azure_tenant_id>" either does not exist or you do not have permission to use it. (2760) (SQLExecDirectW)'))
```

by looking at the error we can definitely say that either the schema is not created or the DB user that they have given us does not have permission may be to create the tables in the DB.

can anyone please suggest what could be going wrong, this is definitely not an issue from the Django or from the django-mssql package as well but an issue from the Azure side. I do not have much experience with Azure/Azure SQL any advice or help would really help me.

Thank you.

**Update 1:**

when I logged into the database and without giving schema when I tried to create tables manually from the SQL server it gave me the permission error. My hunch is that with service principal when I run the migrate command it's not picking the default schema and maybe that's why it could be giving the error. 

**Update 2:**

when I logged in through my user account and when I ran the `select SCHEMA_NAME()` SQL command it gave me the result as null. which means that there is no default schema that has been assigned to my user account. Similarly, I guess the user that the client has given will not have a default schema assigned and maybe that's why when I ran the Django migrate command it was unable to find a schema and gave the error - The specified schema name "<db_user>@<azure_tenant_id>" either does not exist. 

But now my question is as you can see when i ran the migrate command, mssql-django with service principal  actually looked for the schema <db_user>@<azure_tenant_id>, does SQL server support this kind of schema name?

Also when i checked the available schemas in the DB i did not see any schema with the the name <db_user>@<azure_tenant_id>.

**Comment by mShan0** [comment]
Hi @aashayamballi, can you double check that the schema you're trying to access exists? You can do so by running `SELECT name FROM sys.schemas` and it will list it all.

If it does, then here is an older issue that provides some information on how to select your schema using Django: #56

**Comment by aashayamballi** [comment]
> Hi @aashayamballi, can you double check that the schema you're trying to access exists? You can do so by running `SELECT name FROM sys.schemas` and it will list it all.
> 
> If it does, then here is an older issue that provides some information on how to select your schema using Django: #56 

I had checked the list of schemas in our DB in that <db_user>@<azure_tenant_id> was not present i only could see dbo.

Even if we mention schemas For the tables that are created by us but we cannot specify the schemas for the tables that are created by django right? For example when we run the initial migration django creates tables like django_migration, django_session etc so for those tables can we specify the schema name?

**Comment by aashayamballi** [comment]
> Hi @aashayamballi, can you double check that the schema you're trying to access exists? You can do so by running `SELECT name FROM sys.schemas` and it will list it all.
> 
> If it does, then here is an older issue that provides some information on how to select your schema using Django: #56 

I had checked the list of schemas in our DB in that <db_user>@<azure_tenant_id> was not present i only could see dbo.

Even if we mention schemas For the tables that are created by us but we cannot specify the schemas for the tables that are created by django right? For example when we run the initial migration django creates tables like django_migration, django_session etc so for those tables can we specify the schema name?

Also I'm pretty new to Azure SQL or SQL server. In the error if you see mssql-django with AD service principal authentication is trying to connect to <db_user>@<azure_tenant_id> schema by default. Any idea why it would be trying to connect to that particular schema which doesn't exist yet as i have seen.

**Comment by aashayamballi** [comment]
Also from the wiki regarding Azure AD Authentication, Service Principal Authentication

The settings look like this

 DATABASES = {
	    "default": {
	        "ENGINE": "mssql",
	        "NAME": "default",
	        "USER": "Application (client) ID",
	        "PASSWORD": "Client secret",
	        "HOST": "example.database.windows.net",
	        "PORT": "1433",
	        "OPTIONS": {
	            "driver": "ODBC Driver 17 for SQL Server",
	            "extra_params": "Authentication=ActiveDirectoryServicePrincipal",
	        },
	    },
	}

Here the name is the database name right? Or should we specify name as default and just USER, PASSWORD & HOST we've to update?

**Comment by aashayamballi** [comment]
@mShan0 can you please advice/help me on the issue?

Because,

except migrations all the other things are working fine. For example If I manaully create a table and If I run inspectdb it's correct model. Also if I create a model with the result of inspectdb and If I use django shell to query the model I'm getting the resutls too.

**Comment by aashayamballi** [comment]
below is the entire stack tracke

```
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, sessions
Running migrations:
Traceback (most recent call last):
  File "C:\Projects\src\backend\venv\lib\site-packages\django\db\backends\utils.py", line 87, in _execute
    return self.cursor.execute(sql)
  File "C:\Projects\src\backend\venv\lib\site-packages\mssql\base.py", line 619, in execute
    return self.cursor.execute(sql, params)
pyodbc.ProgrammingError: ('42000', '[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]The specified schema name "<db_user>@<azure_tenant_id>" either does not exist or you do not have permission to use it. (2760) (SQLExecDirectW)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Projects\src\backend\venv\lib\site-packages\django\db\migrations\recorder.py", line 70, in ensure_schema
    editor.create_model(self.Migration)
  File "C:\Projects\src\backend\venv\lib\site-packages\mssql\schema.py", line 1103, in create_model
    self.execute(sql, params or None)
  File "C:\Projects\src\backend\venv\lib\site-packages\mssql\schema.py", line 1167, in execute
    cursor.execute(sql, params)
  File "C:\Projects\src\backend\venv\lib\site-packages\django\db\backends\utils.py", line 103, in execute   
    return super().execute(sql, params)
  File "C:\Projects\src\backend\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute    
    return self._execute_with_wrappers(
  File "C:\Projects\src\backend\venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Projects\src\backend\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute   
    with self.db.wrap_database_errors:
  File "C:\Projects\src\backend\venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Projects\src\backend\venv\lib\site-packages\django\db\backends\utils.py", line 87, in _execute   
    return self.cursor.execute(sql)
  File "C:\Projects\src\backend\venv\lib\site-packages\mssql\base.py", line 619, in execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: ('42000', '[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]The specified schema name "<db_user>@<azure_tenant_id>" either does not exist or you do not have permission to use it. (2760) (SQLExecDirectW)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Projects\src\backend\manage.py", line 22, in <module>
    main()
  File "C:\Projects\src\backend\manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "C:\Projects\src\backend\venv\lib\site-packages\django\core\management\__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "C:\Projects\src\backend\venv\lib\site-packages\django\core\management\__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Projects\src\backend\venv\lib\site-packages\django\core\management\base.py", line 402, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Projects\src\backend\venv\lib\site-packages\django\core\management\base.py", line 448, in execute    output = self.handle(*args, **options)
  File "C:\Projects\src\backend\venv\lib\site-packages\django\core\management\base.py", line 96, in wrapped 
    res = handle_func(*args, **kwargs)
  File "C:\Projects\src\backend\venv\lib\site-packages\django\core\management\commands\migrate.py", line 349, in handle
    post_migrate_state = executor.migrate(
  File "C:\Projects\src\backend\venv\lib\site-packages\django\db\migrations\executor.py", line 107, in migrate
    self.recorder.ensure_schema()
  File "C:\Projects\src\backend\venv\lib\site-packages\django\db\migrations\recorder.py", line 72, in ensure_schema
    raise MigrationSchemaMissing(
django.db.migrations.exceptions.MigrationSchemaMissing: Unable to create the django_migrations table (('42000', '[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]The specified schema name "<db_user>@<azure_tenant_id>" either does not exist or you do not have permission to use it. (2760) (SQLExecDirectW)'))
```

**Comment by aashayamballi** [comment]
> when I logged in through my user account and when I ran the `select SCHEMA_NAME()` SQL command it gave me the result as null.

As I said in UPDATE 2 `when I logged in through my user account and when I ran the select SCHEMA_NAME() SQL command it gave me the result as null.` is there any chance because of default schema is not being set?

**Comment by aashayamballi** [comment]
okay I know why this service principal auth is trying for <db_user>@<azure_tenant_id> schema. I logged in to our DB from my company account and for testing I tried creating a table without giving any schema. It gave me the below error. Most probably because there is no default scheam that has not been set for that DB user maybe we're getting that errror.

![image](https://user-images.githubusercontent.com/26691110/206961801-fe0079c1-6c98-466a-a3e1-122ce73d266b.png)

**Comment by aashayamballi** [comment]
In the Wiki I read about for service principal authentication - 

```
In Azure SQL make sure your app has the right permission
CREATE USER [AuthAPP] FROM EXTERNAL PROVIDER
EXEC sp_addrolemember 'dbmanager', 'AuthAPP'
```
@mShan0 can you please tell me what this command does? as I told in previous commands our client direclty gave this db to us. If I get to know why this command is used, I can ask them whether this command has been run or not while creating the db user.

**Comment by aashayamballi** [comment]
Well, my guess was correct, there was no schema that was assigned to our service principal. I reached out to the infra team of our client and asked them to set dbo as the default schema for the AD group. After setting the dbo as the default schema, I was able to successfully run the initial migration.
