### ISSUE TITLE
Error doing queries to legacy SQL Server 2008 R2 database.

### ISSUE THREAD

**Issue by adelkhayata76** [microsoft/mssql-django#220]
We are using now mssql-django ver: 1.1.1

I got this issue when tried to update to mssql-django 1.2, because we are still using legacy SQL Server 2008 R2 database.

pyodbc.ProgrammingError: ('42000', "[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Incorrect syntax near 'OFFSET'. (102) (SQLExecDirectW)")

There is a suggestion from another Issue post: [https://github.com/microsoft/mssql-django/issues/12#issuecomment-1254274612](url)

I have created a Pull request to fix the issue: [https://github.com/microsoft/mssql-django/pull/218](url)

Would you please take a look at the PR?

Best Regards.

**Comment by khanhmaibui** [comment]
Hi @adelkhayata76, thank you for the review and reaching out! We are currently looking into the PR.

**Comment by mShan0** [comment]
Merged PR #220
