### ISSUE TITLE
Default driver is not what the README claims

### ISSUE THREAD

**Issue by dimbleby** [microsoft/mssql-django#23]
README says:

> - driver
> 
> String. ODBC Driver to use ("ODBC Driver 17 for SQL Server", "SQL Server Native Client 11.0", "FreeTDS" etc). Default is "ODBC Driver 17 for SQL Server".

[code](https://github.com/microsoft/mssql-django/blob/b37cecf94d13197e8cd4cb6cf1cbb8b27329210b/mssql/base.py#L255) says:
```python
driver = options.get('driver', 'ODBC Driver 13 for SQL Server')
```

(I found this because 17 is the value that one actually needs in an Azure App Service.  But since the README told me that was the default, I left it alone; and then it didn't work.)

**Comment by absci** [comment]
Thanks for the report, I'll change the default value accordingly to match the README file.
