### ISSUE TITLE
No longer compatible with Django 2.2, but still claims compatibility

### ISSUE THREAD

**Issue by nburlett** [microsoft/mssql-django#231]
The commit for  Added hashing function support #152  [added an import for MD5 and other functionality](https://github.com/microsoft/mssql-django/commit/d1c0665789fd09f80f4841d329ea4bfb82fb4486#diff-18a67edd87e19a2f28789fdf047daa1bf12bf13e150bf50dcd6cf6f73fd3c171R12) that is not present in Django 2.2 (It was [added in 3.0](https://docs.djangoproject.com/en/3.0/releases/3.0/#models) . 

Either the import needs to be conditional based on django version, or the setup.py shouldn't claim to support Django 2.2

**Comment by mShan0** [comment]
Good point. Opened a PR for it.
