### ISSUE TITLE
[QUESTION] Cert issued by untrusted authority

### ISSUE THREAD

**Issue by Ulryx** [microsoft/mssql-django#233]
**Question**
Good Morning,

I'm trying to connect to a MSSQL but am getting:

'The certificate chain was issued by an authority that is not trusted'

I had figured the 'Trusted_Connection' would get around this but I'm having no luck, would anyone be able to point me in the right direction?

Thank you in advance.

**Comment by Ulryx** [comment]
And figured it out, in case anyone searching around this only presents with ODBC Driver 18, 17 will connect.

**Comment by tremblaysimon** [comment]
With ODBC Driver 18 for SQL Server what I understand is that it's using Encrypt=true by default. If you specify extra parameters like that one (for local testing) it will connect without problems:

```
        "OPTIONS": {"driver": "ODBC Driver 18 for SQL Server",
                    'extra_params': "TrustServerCertificate=yes" },
```

**Comment by Ulryx** [comment]
Thank you! I belive I found another work around for this and have learned a ton since then, but I appreciate you coming back in case anyone else needs this in the future.
