### ISSUE TITLE
JSON Field model cause error during migrate

### ISSUE THREAD

**Issue by skasidej** [microsoft/mssql-django#24]
Has anyone come across with an error from `models.JSONField()` which is caused from models.py. Even the migrations file defined the field as `models.TextField()`. Because if my understanding is right, there is no JSON column inside MS SQL.

An example of error while migrating
`
ERRORS:
app.SomeModel: (fields.E180) SQL Server does not support JSONFields.
script returned exit code 1
`

The thing is, I don't want to loads and dumps JSON back and forth from the column and JSONField is doing the tedious work for me. Is there an alternative solution for this kind of problem?

**Comment by randlet** [comment]
The repository this one was forked from has the JSONField from Django 3.1 implemented: https://github.com/ESSolutions/django-mssql-backend/pull/82 so that fix could likely get ported over here.

**Comment by absci** [comment]
Thanks for your comment. We are currently working on JSONField related issues.

**Comment by lucasfijen** [comment]
For the time beeing I'm using https://pypi.org/project/jsonfield/, which seems to still work on 3.1, and actively dumps the json into a textfield and loads it again when called.

**Comment by absci** [comment]
This is fixed in the `dev` branch.

**Comment by byt3pool** [comment]
@absci Is there any plan to release this soon?

I set up my system today (Django 3.2.4, mssql-django 1.0.b1) and get the same error: "SQL Server does not support JSONFields."

**Comment by absci** [comment]
> @absci Is there any plan to release this soon?
> 
> I set up my system today (Django 3.2.4, mssql-django 1.0.b1) and get the same error: "SQL Server does not support JSONFields."

A new version 1.0rc1 released today, give it a try.
