### ISSUE TITLE
Is the "HOST" part of the docs unclear or wrong?

### ISSUE THREAD

**Issue by phlawlessDevelopment** [microsoft/mssql-django#241]
**Question**
Maybe I'm missing something...

The section HOST reads --
String. SQL Server instance in "server\instance" format.

which seems like it can't be right, "\" is an escape character.
Should it be "server\\instance" ?  

Then later in the documentation , you have an example 

```DATABASES = {
        'default': {
            'ENGINE': 'mssql',
            'NAME': 'mydb',
            'USER': 'user@myserver',
            'PASSWORD': 'password',
            'HOST': 'myserver.database.windows.net',
            'PORT': '',

            'OPTIONS': {
                'driver': 'ODBC Driver 17 for SQL Server',
            },
        },
    }
```

In this example there's no slash at all in the HOST section, it's all dots..

As an example my mssql is running in a docker container, my server name is "3209963da4f4" (the guid of the container) and my instance name should be the default (MSSQLSERVER) as I never set one.

Should my host be 
"3209963da4f4\MSSQLSERVER" 
or
"3209963da4f4\\\MSSQLSERVER"
or 
"3209963da4f4.MSSQLSERVER"
or
Something else entirely?

Thanks in advance :)

**Relevant Issues and Pull Requests**

**Comment by mShan0** [comment]
Hi @phlawlessDevelopment, the reason you're seeing dots in the example you've shown is because that's actually the URL to an Azure SQL server. In your case, you can use a single backslash if you're not escaping a special character (e.g. \n, \r, etc.) but you can also use `\\` to be safe.

**Comment by phlawlessDevelopment** [comment]
@mShan0 , thanks so much for getting back to me so quickly.
Ah, of course ! That makes a lot of sense.
I'm still getting a "[ODBC Driver 18 for SQL Server]Login timeout expired (0)" error, but this confirms I've got this part right, so again thanks.

Do you know if there's any way to get more verbose output about that error?

**Comment by mShan0** [comment]
That error usually means that Django can't find the host provided. Have you tried just the GUID? The instance name may not be necessary to connect to a container.

**Comment by phlawlessDevelopment** [comment]
You're right about the fix, thank you again.
Although I think the reason might be something else,
I've left to office for the night and so I don't have the exact link to hand. (I'll post it here for future reference tomorrow) but found something that said that specific instance name is what shows up when it's an "unnamed instance" so removing it fixed the problem.. anyway , I cannot thank you enough for taking the time.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
