### ISSUE TITLE
[FEATURE REQUEST] Support Django 4.2

### ISSUE THREAD

**Issue by cw-kbra-10887** [microsoft/mssql-django#248]
Django 4.2 has been released and this project does not support it.
This appears to be abandoned, so if anyone has suggestions for an alternative, I'm listening.

**Comment by mShan0** [comment]
Not sure where you got the idea that this project was abandoned. We're working on fixing the test failures that were raised by 4.2 right now. You can try the `django42` branch out in the meantime if you need 4.2 immediately. Otherwise, our release is scheduled for May.

**Comment by ryancheley** [comment]
Really looking forward to this release. Are you planning on supporting the new features for `db_comment` and `db_table_comment`? I don't see any references in the `django42` branch. Thanks for your work on this!

**Comment by mShan0** [comment]
Thanks for bringing that up. We've added it to our backlog

**Comment by danyi1212** [comment]
@mShan0 Any updates about Django 4.2 support?

**Comment by khanhmaibui** [comment]
Hi @danyi1212, we just released our new version `1.3` with Django 4.2 support!
