### ISSUE TITLE
Does the latest mssql-django supports Django 4.2

### ISSUE THREAD

**Issue by JJMLMAO** [microsoft/mssql-django#258]
When I was working on my django project, it seemed like when i pip install mssql-django, it wouldn't work as it mentioned that django 4.2 exists. Then i tried to create another project folder, and i did the same by installing mssql-django, it worked, but i downgraded my django from 4.2 to 4.1.8 . I hope this can resolved, where my current project I'm using Django 4.2 where I couldn't downgrade it to Django 4.1.8

Thank you so much

**Comment by mShan0** [comment]
Hi @JJMLMAO, we're currently working on supporting 4.2. You can try the django42 branch if you need 4.2 immediately. Otherwise, our release is scheduled for May.

**Comment by JJMLMAO** [comment]
> Hi @JJMLMAO, we're currently working on supporting 4.2. You can try the django42 branch if you need 4.2 immediately. Otherwise, our release is scheduled for May.

May I know when exactly it will be released? And if I were to use the one you've suggested to me, 
Will it be stable to support django4.2?
And also where should I install or read the documentation for django42 branch?

Sorry if I ask such funny question, I'm quite new to this.
Thank youu !

**Comment by JJMLMAO** [comment]
Thank you so much !
