### ISSUE TITLE
[QUESTION] Can I use driver "SQL Server"?

### ISSUE THREAD

**Issue by puatrap** [microsoft/mssql-django#262]
**Question**

My environment does not allow me to install other drivers, so I can only use the built-in 'SQL Server' to connect to SQL Server. What should I do?
**Relevant Issues and Pull Requests**

**Comment by Sourdough1882** [comment]
You need to specify driver and extra parameters in your options (DSN, server etc) in your database configuration as follows:

```python
DATABASES = {
    'default': {
        # Reference: https://pypi.org/project/mssql-django/
        'OPTIONS': {
            'driver': 'SQL Server', 
            'extra_params': 'Server=value;' # Parameters which may be required for your connection
        }
    }
}
```
But keep in mind that SQL Server can have outdated datetime table format for django, so you might need to ask your system administrator to install ODCB driver in your system.

**Comment by puatrap** [comment]
DATABASES = {
    'default': {
        'ENGINE': 'mssql',
        'NAME': 'AdventureWorks2005',
        'HOST':  '192.168.00\SQLEXPRESS',
        'USER': 'sa',
        'PASSWORD': 'qwe123',
        'PORT': '1433',
        'OPTIONS': {
        'driver': 'SQL Server', 
        'extra_params': 'SERVER=192.168.00\SQLEXPRESS;Database=AdventureWorks2005;Uid=sa;Pwd=qwe123' # Parameters which may be required for your connection

        },
    }
}

Why can't I connect?

**Comment by puatrap** [comment]
It show me "The database driver doesn't support modern datatime types"
So I want to use SQLOLEDB to connect to the database. What should I do?

**Comment by mShan0** [comment]
Hi @puatrap, unfortunately this driver does not support OLEDB

**Comment by puatrap** [comment]
But why can 'pyodbc' retrieve datetime data using 'SQL Server'?

**Comment by mShan0** [comment]
I'm assuming when you say `SQL Server`, you're talking about the driver with the filename `SQLSRV32.DLL`. That's ODBC 10, which is a very old version but still ODBC. You can check what ODBC drivers you can use with this project [here](https://github.com/microsoft/mssql-django#features)
