### ISSUE TITLE
Update databae with new tables or columns in pre-existing tables.

### ISSUE THREAD

**Issue by sajalT05** [microsoft/mssql-django#264]
There are some features which are not supported yet. Please check the [Limitations](https://github.com/microsoft/mssql-django#limitations) first to see if your bug is listed.

Hello,
Situation: I've already created tables with py manage.py makemiragtions/migrate. All tables are created from models.py file. Problem: But now again when I create new tables from or add new columns after specifying them models.py file and running scripts (py manage.py makemiragtions/migrate) in CLI, new tables  or columns in pre-existing tables are not getting created.
Error: No error in terminal after running scripts. But when I try to access data with endpoints, django error page comes up - column [___] in table  [___] doesn't exist. 
Question: Is this a bug, or a constraint, or I'm missing something important.

**Software versions**
* Django: latest
* mssql-django: latest
* python: latest
* SQL Server: latest
* OS: linux
* using azure devops to deploy django app
* using azure app service to host django app
* using azure cli for all running scripts

**Table schema and Model | please ignore type here********

# old
class model(Model):
    field1 = charfield()
# new
class model(Model):
    field1 = charfield()
    field2 = charfield()

**Database Connection Settings**
`
// Paste your database settings from Settings.py here.
`
* same as in documentation * 

**Problem description and steps to reproduce**

1. database connection made.
2. tables created in first run of script (py manage.py makemiragtions/migrate)
3. create new models or add new fields in existing models, in models.py file.
4. again run script (py manage.py makemiragtions/migrate)
5. new tables or columns not getting created.

**Expected behavior and actual behavior**

1. new tables or columns should be cretaed.

**Error message/stack trace**

1. column [___] in table  [___] doesn't exist

**Any other details that can be helpful**

**Comment by mShan0** [comment]
Can you post exactly what your models.py has? Is there anything like the following in your models?
```
class Meta:
    managed = False
```
Can you also run `makemigrations -v 3` to show some more details?

**Comment by dauinsight** [comment]
Hello @sajalT05, it's been some time since we've heard from you. If you're still experiencing issues, please respond within 5 days, otherwise, we'll need to close this issue.
