### ISSUE TITLE
Python 3.9 Pipelines

### ISSUE THREAD

**Issue by msopko81** [microsoft/mssql-django#27]
I came across this page: https://github.com/microsoft/mssql-django/runs/2322199369 and it looks like you have pipelines for python versions 3.6 through 3.8, but not 3.9.

**Comment by absci** [comment]
Good suggestion, I'll Python 3.9 to the pipeline.

**Comment by absci** [comment]
Python 3.9 added to the pipeline. https://github.com/microsoft/mssql-django/commit/0153047808842dfb23c538b88e08bf5d118fc432
