### ISSUE TITLE
queryset return by bluck_create method doesn't have id/pk

### ISSUE THREAD

**Issue by tumzied** [microsoft/mssql-django#277]
**Software versions**
* Django: 4.0.10
* mssql-django:  1.2 | 1.3
* python: 3.8
* SQL Server: 17
* OS: Win 10

**Table schema and Model**

```
class MyText(model.Model):
   text = models.CharField(max_length=500)
```

**Database Connection Settings**
```

DATABASES = {
    'default': {
        'ENGINE': 'mssql',
        'NAME': os.environ.get('DATABASE_NAME', 'mydb'),
        'USER': os.environ.get('DATABASE_USER_NAME', 'sa'),
        'PASSWORD': os.environ.get('DATABASE_PASSWORD', '123456'),
        "HOST": os.environ.get('DATABASE_HOST_ADDRESS', 'SQLEXPRESS'),
        "PORT": os.environ.get('DATABASE_PORT', '1433'),
        "OPTIONS": {
            "driver": "ODBC Driver 17 for SQL Server",
        },
    },
}
```

**Problem description and steps to reproduce**
When using bulk_create method, the returned queryset doesn't have id / pk.
```
from api.models.MyText import MyText

a = [MyText(text="someting x"), MyText(text="someting y")]

b = MyText.objects.bulk_create(a)

// [<MyText: MyText object (None)>, <MyText: MyText object (None)>]

b[0].id // None

```

**Expected behavior and actual behavior**

```
...
b = MyText.objects.bulk_create(a)

// [<MyText: MyText object (1)>, <MyText: MyText object (2)>]

b[0].id // 1

```
**Any other details that can be helpful**

I have also test this behavior with `mssql-django==1.1.3` version and found that the bulk create able to return queryset with the id/pk.   Newer version of `mssql-django` packages (1.2, 1.3) is not  return queryset with the id/pk.

**Comment by mShan0** [comment]
Hi @tumzied, I'm able to reproduce this locally. It seems like there is an id/pk being generated and saved. It's just that it's not accessible when doing `b[0].id`. I can still grab the id if I query it like this; `MyText.objects.get(text="someting x").id`. Will look into why b[0].id doesn't work

**Comment by tumzied** [comment]
Hello @mShan0, I'm aware that id/pk are generated and saved in the database, as well as your suggestion for extracting 'id' using `MyText.objects.get(text="someting x").id`. The business logic I'm attempting to solve requires the ids of newly created objects generated via the `bulk_create` function. Using `.get /.filter` to get objects would also be difficult due to duplicated data, complex query and an extra database request.

**Comment by mShan0** [comment]
So I did some more digging and we did change the default behaviour from 1.1.3 to 1.2. You can restore the original functionality by setting `"return_rows_bulk_insert" = True` in the options of your connection setting. Our readme has more info on this as shown below. Let me know if this works for you.

From our readme doc:

**return_rows_bulk_insert**

Boolean. Sets if backend can return rows from bulk insert. Default value is False which doesn't allows for the backend to return rows from bulk insert. Must be set to False if database has tables with triggers to prevent errors when inserting.
```
# Examples
"OPTIONS": {
    # This database doesn't have any triggers so can use return
    # rows from bulk insert feature
    "return_rows_bulk_insert": True
}

"OPTIONS": {
    # This database has triggers so leave return_rows_bulk_insert as blank (False)
    # to prevent errors related to inserting and returning rows from bulk insert
}
```


Just an FYI:
The PR that changed this behaviour: https://github.com/microsoft/mssql-django/pull/161
Why it was changed: https://github.com/microsoft/mssql-django/issues/130

**Comment by tumzied** [comment]
Thanks @mShan0
