### ISSUE TITLE
[QUESTION] Trusted connection and specifying databsae

### ISSUE THREAD

**Issue by CristianArean** [microsoft/mssql-django#279]
**Question**
Hi! 

I want to ask if there is any way of connecting to a database using TrustedConnection like if you are using Pyodbc, that detects your windows login account and use it to authenticate you in the database.

And another question I have it's... In the sql server I have several databases in the same sqlserver. How can I specify witch one use for each model like I do with the schemas and tables?  
This is how I did it for schemas and tables:

```
class CarPrices(models.Model):
    class Meta:
        db_table = 'CarPrices'
        db_schema = 'Prices'
```

**Comment by mShan0** [comment]
Hi @CristianArean, I believe you can just leave out the `USER` and `PASSWORD` out from your connection config and it will try to use Windows Auth. Just have the Trusted_Connection param set to yes like this: 
```
"OPTIONS": { "extra_params": "Trusted_Connection=Yes"}
```
This driver uses pyODBC to connect so anything that works with pyODBC should work with this driver.

For multiple db's, Django's documentation shows multiple ways of handling it here:
https://docs.djangoproject.com/en/4.2/topics/db/multi-db/

Hope this helps

**Comment by mShan0** [comment]
Feel free to re-open this issue if you have any follow-up questions.
