### ISSUE TITLE
Data types suffixes are not being added when creating an auto increment field

### ISSUE THREAD

**Issue by MervinDelfin** [microsoft/mssql-django#282]
There are some features which are not supported yet. Please check the [Limitations](https://github.com/microsoft/mssql-django#limitations) first to see if your bug is listed.

**Software versions**
* Django: 4.2.3
* mssql-django: 1.3
* python: 3.11
* OS: Windows 10

**Problem description and steps to reproduce**
When adding an AutoField or BigAutoField to a model the 'IDENTITY (1, 1)' suffix is not being added to the sql code of the migration.

**This is the migration:**
```python
migrations.AddField(
          model_name='arkusz1',
          name='id',
          field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
          preserve_default=False,
      ),
```

**The sql code generated with the `python3 manage.py sqlmigrate` command:**
```sql
BEGIN TRANSACTION
--
-- Add field id to arkusz1
--
ALTER TABLE [Arkusz1$] ADD [id] bigint NOT NULL PRIMARY KEY;
COMMIT;
```

**The expected sql code:**
```sql
BEGIN TRANSACTION
--
-- Add field id to arkusz1
--
ALTER TABLE [Arkusz1$] ADD [id] bigint IDENTITY (1, 1) NOT NULL PRIMARY KEY;
COMMIT;
```

**Any other details that can be helpful**
I see the suffixes are defined in `base.py` but they are not being used:
```python
data_types_suffix = {
        'AutoField': 'IDENTITY (1, 1)',
        'BigAutoField': 'IDENTITY (1, 1)',
        'SmallAutoField': 'IDENTITY (1, 1)',
    }
```

**Comment by mShan0** [comment]
Thanks for the report. We do have some AutoField features that are not fully implemented yet (you can see the list here https://github.com/microsoft/mssql-django#limitations) but we'll take a look into this.

**Comment by dauinsight** [comment]
Hi @MervinDelfin ,we'll have a fix for this in our next release.
