### ISSUE TITLE
Index error when altering nullable field to non-nullable

### ISSUE THREAD

**Issue by rjschave** [microsoft/mssql-django#286]
There are some features which are not supported yet. Please check the [Limitations](https://github.com/microsoft/mssql-django#limitations) first to see if your bug is listed.

**Software versions**
* Django: 4.2.3
* mssql-django: 1.3
* python: 3.11
* SQL Server: 2019
* OS: Windows

**Table schema and Model**

Before (Step 2, below)
```python
class Demo(models.Model):
    name = models.CharField(max_length=50)
    another_field = models.IntegerField(null=True)

    class Meta:
        indexes = [
            models.Index(fields=['name', 'another_field'], name='my_custom_index')
        ]
```

After (Step 4, below)
```python
class Demo(models.Model):
    name = models.CharField(max_length=50)
    another_field = models.IntegerField()

    class Meta:
        indexes = [
            models.Index(fields=['name', 'another_field'], name='my_custom_index')
        ]
```

**Database Connection Settings**

```python
DATABASES = {
    'default': {
        'ENGINE': 'mssql',
        'HOST': 'localhost',
        'PORT': '1433',
        'NAME': 'mssql_django_index_error',
        'USER': 'sa',
        'PASSWORD': 'change_me#2023',
        'OPTIONS': {
            'OPTIONS': {'driver': 'ODBC Driver 17 for SQL Server'},
        },
    },
}
```

**Problem description and steps to reproduce**
1. Add a nullable field to a model.
2. Add an index that references the new field in the model's Meta class.
3. Make and apply migrations.
4. Remove the nullable option from the field.
5. Make and apply migrations.

**Expected behavior and actual behavior**

I expect the 2nd migration to drop the index before altering the field, and the recreate the index afterwards.

Instead, the migration is attempting the alter the field with the index in place:
```sql
BEGIN TRANSACTION
--
-- Alter field another_field on demo
--
ALTER TABLE [polls_demo] ALTER COLUMN [another_field] int NOT NULL;
COMMIT;
```

**Error message/stack trace**

django.db.utils.ProgrammingError: ('42000', "[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]The index 'my_custom_index' is dependent on column 'another_field'. (5074) (SQLExecDirectW)")

**Any other details that can be helpful**
I created a project to reproduce this issue - https://github.com/eclipseconsulting/mssql_django_index_error

If an index is created directly on the column (db_index=True) instead of the model's Meta class, the 2nd migration will correctly drop the index, alter the column, and then recreate the index.

If this issue were occurring directly in our project, we could work around it by manipulating the model and/or migrations.  We encountered this error in a 3rd party library (Wagtail version 4.04, migration: wagtailcore 0072), so we do not have direct control of the models and migrations.

**Comment by mShan0** [comment]
Thanks for the detailed report. Looking into this now.

**Comment by mShan0** [comment]
Merged fix
