### ISSUE TITLE
Placeholder for Django 5.0 db_default support

### ISSUE THREAD

**Issue by sparrowt** [microsoft/mssql-django#302]
This is currently a bit light on detail but I wanted to put in a ticket early so that this is tracked.

Since this ticket was fixed in May 2023 https://code.djangoproject.com/ticket/470#comment:69 there is now an option `db_default` coming in Django 5.0 https://docs.djangoproject.com/en/dev/releases/5.0/#database-computed-default-values

If the description in this open PR is still correct https://github.com/michiya/django-pyodbc-azure/pull/38 then we may need to port those (or similar) changes to this repo, in order to drop the DEFAULT constraint so that removing a field with such a constraint does not fail.

**Comment by mShan0** [comment]
Thanks for the heads up!
