### ISSUE TITLE
[QUESTION] Is it possible to return Auto Field primary keys using bulk_create?

### ISSUE THREAD

**Issue by ahibrahimm** [microsoft/mssql-django#303]
**Question**
Is it possible to return AutoField primary keys _(auto incremented IDs)_ using bulk_create?

From Django's docs, looks like some databases support returning the row IDs using `bulk_create`, but I'm not sure about SQL Server.

I checked the [features page](https://github.com/microsoft/mssql-django/blob/dev/mssql/features.py) and found two relevant attributes: `has_bulk_insert` and `can_return_rows_from_bulk_insert`. So, I can tell bulk is supported but it can't return all rows. However, I'm not sure if it could at least just return the IDs or not. Maybe `can_return_rows_from_bulk_insert` means it can't, but I want to make sure.

**Comment by mShan0** [comment]
You should be able to but we can double check on our end. Were you running into issues doing so?

**Comment by ahibrahimm** [comment]
The `options.return_rows_bulk_insert` is exactly what I was lookign for - thank you!
