### ISSUE TITLE
Flat out stopped working

### ISSUE THREAD

**Issue by kevCurnow** [microsoft/mssql-django#304]
Was trying to implement DataTables into a project and everything stopped working. When I tried to runserver, I got the error that mssql isn't a recognized backend. However it has been working for me, so I simply tried to pip install mssql-django again. That failed apparently because of pyodbc saying that my Visual C++ wasn't up to date, so I tried installing the latest version. Nothing.

Any help would be greatly appreciated

**Comment by kevCurnow** [comment]
started a new project from scratch and it still was having issues with install. ERROR: Could not build wheels for pyodbc, which is required to install pyproject.toml-based projects

**Comment by kevCurnow** [comment]
If it helps, I am using the newest version of django 4.2.5

**Comment by kevCurnow** [comment]
Also using python 3.12.0, is it not supported yet?

**Comment by rjschave** [comment]
> Also using python 3.12.0, is it not supported yet?

Looks like your system isn't setup to compile pyodbc from source.  Looking at the files available for pyodbc (https://pypi.org/project/pyodbc/4.0.39/), I don't see wheels for Python 3.12.  

Python 3.12 was released just 2 days ago.  There's an open PR to add support for 3/12 (https://github.com/mkleehammer/pyodbc/pull/1275).

Do you get an error with Python 3.11?

**Comment by kevCurnow** [comment]
Silly me, just needed to rollback to 3.11.6
