### ISSUE TITLE
CheckConstraint produces syntax error

### ISSUE THREAD

**Issue by iamjameswalters** [microsoft/mssql-django#309]
Hi there. I have a model with a few BooleanFields, one that indicates phone_service, and two others for transfer types. If phone_service is selected, then at least one of the two transfer options needs to be selected. I wrote the following CheckConstraint:

```
        constraints = [
            models.CheckConstraint(
                name="if_phone_require_transfer",
                check=(
                    models.Q(phone_service=False)
                    | (models.Q(warm_transfers=True) | models.Q(cold_transfers=True))
                ),
            ),
        ]
```

But when I try to submit my form, I get the following error message in the console:

```
Got a database error calling check() on <Q: (AND: (OR: ('phone_service', False), ('warm_transfers', True), ('cold_transfers', True)))>: ('42000', "[42000] [Microsoft][ODBC query_utils.py:139                    Driver 17 for SQL Server][SQL Server]Incorrect syntax near '='. (102) (SQLExecDirectW); [42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Statement(s) could 
                    not be prepared. (8180)")
```

Is this related to `msql-django`?

The [README](https://github.com/microsoft/mssql-django#limitations) says that database-level constraints don't work--is that what the issue is here? I have other CheckConstraints that do work.

**Software versions**
* Django: 4.2.6
* mssql-django: 1.3
* python: 3.11.3
* SQL Server: 15.0.2104.1
* OS: Windows 10

**Comment by mShan0** [comment]
Hi @iamjameswalters, some CheckConstraint cases aren't fully implemented yet on our end

**Comment by iamjameswalters** [comment]
Gotcha. In that case, I'll operate without this check constraint for now. Thanks for the info!

**Comment by dauinsight** [comment]
Hi @iamjameswalters, you can expect a fix for this in the next release.

**Comment by iamjameswalters** [comment]
Wonderful! Thanks to all involved 👏
