### ISSUE TITLE
Unable to override managed = False when using django-mssql

### ISSUE THREAD

**Issue by ryancheley** [microsoft/mssql-django#311]
There are some features which are not supported yet. Please check the [Limitations](https://github.com/microsoft/mssql-django#limitations) first to see if your bug is listed.

**Software versions**
* Django: 4.2
* mssql-django: 1.3
* python: 3.10
* SQL Server: 2019
* OS: Windows 11

**Table schema and Model**

**Database Connection Settings**
`
// Paste your database settings from Settings.py here.
`

```
    "django": {
        "ENGINE": "mssql",
        "HOST": env("LOCAL_HOST_NAME"),
        "PORT": "1433",
        'USER': 'sa',
        'PASSWORD': 'YourStrongPassword123',
        "OPTIONS": {
            "driver": "ODBC Driver 17 for SQL Server",
        },
    },
```

**Problem description and steps to reproduce**

I have a set of models which are 'unmanaged', i.e. in the model Meta class the `managed = False`. When using pytest I have a conftest.py file which changes this to be  `managed = True`, like this:

```
import pytest


@pytest.fixture(autouse=True, scope="session")
def django_test_environment(django_test_environment):
    from django.apps import apps

    get_models = apps.get_models

    for m in [m for m in get_models() if not m._meta.managed]:
        m._meta.managed = True
```

When I use an in memory SQLite database the tests pass. The connection string looks like this:

```
    "django": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "django.sqlite3",
    },
```
When I change this to use the Dockerized MS SQL server an error is generated indicated that the object doesn't exist. 

**Expected behavior and actual behavior**

The MS SQL database will have passing tests similar to the in memory SQLite database

**Error message/stack trace**

```
ERROR legacy/tests/test_admin.py::test_rerun - django.db.utils.ProgrammingError: ('42S02', "[42S02] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid object name 'SSRSDeliveryAutomation'. (208...
```

**Any other details that can be helpful**

It appears that the overridding of the `managed` is not being accepted when using MS SQL in a docker instance.

**Comment by dauinsight** [comment]
Hi @ryancheley , thank you for bringing this to our attention. We will investigate this issue and report back to you.

**Comment by ryancheley** [comment]
@dauinsight great! if there’s any more information I can provide, please let me know.

**Comment by dauinsight** [comment]
Hi Ryan, I couldn't create the table with `m._meta.managed = True` using your test runner code for SQLite or SQL Server.  If using `django-pytest` ensure that the `--no-migrations` flag is added.

Otherwise, what I recommend is using `schema_editor` to create the unmanged models in the `setUp()` method.

**Comment by ryancheley** [comment]
@dauinsight not sure what happened, but I'm not getting the error now. Sorry for the false report and thanks for responding back. This is a great library and I'm very glad that it exists!
