### ISSUE TITLE
Support Django 5.x

### ISSUE THREAD

**Issue by dakotahorstman** [microsoft/mssql-django#321]
Django 5.0 has been released and should be supported. This is, currently, the only dependency I have blocking migration, so please keep us posted on progress! :)

**Comment by dauinsight** [comment]
Hi @dakotahorstman, support for Django 5.0 is almost complete. We will let you know when it is released. Happy Holidays!

**Comment by mShan0** [comment]
Django 5.0 has been released with MSSQL-Django 1.4!
