### ISSUE TITLE
[FA001] [Microsoft][ODBC Driver 17 for SQL Server]Cannot use Authentication option with Integrated Security option

### ISSUE THREAD

**Issue by NZSmartie** [microsoft/mssql-django#33]
Using:
- Python 3.8
- Windows 10
- mssql-django 1.0b1

In setting up an existing Django application to use SQL server on Azure through AppService, I've got a test databse set up and i'm able to authenticate through Azure when using SQL Management Studio. 

Following the example set in https://github.com/microsoft/mssql-django/wiki/Azure-AD-Authentication, for `settings.py` I have:
```python
 DATABASES = {
        'default': {
            'ENGINE': 'mssql',
            'NAME': 'test',
            'HOST': 'example.database.windows.net',
            'PORT': '',
            'USER': 'my.ad.user@my.domain',

            'OPTIONS': {
                'driver': 'ODBC Driver 17 for SQL Server',
                "extra_params": 'Authentication=ActiveDirectoryInteractive',
            },
        },
    }
```

when running django with `python manage.py migrate` I get the following:
```
[FA003] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Password option must not be specified, if Authentication option is 'ActiveDirectoryInteractive'. (0) (SQLDriverConnect); [FA003] [Microsoft][ODBC Driver 17 for SQL Server]Invalid connection string attribute (0)
```

Okay sure. the recent changes in b41e8b4cd31ce5e3c7e074c4a82e7da303654a54 haven't been released/published yet.
I thought i'd be clever and set the `UID` in the `extra_params` so that a stray `PWD` doesn't get concatenated. 

https://github.com/microsoft/mssql-django/blob/00bbdca7206192b12752d75ba33c78755e41e20d/mssql/base.py#L287-L289

`settings.py` now has the following:
```python
 DATABASES = {
        'default': {
            'ENGINE': 'mssql',
            'NAME': 'test',
            'HOST': 'example.database.windows.net',
            'PORT': '',

            'OPTIONS': {
                'driver': 'ODBC Driver 17 for SQL Server',
                "extra_params": 'UID=my.ad.user@my.domain;Authentication=ActiveDirectoryInteractive',
            },
        },
    }
```

But now I get the following issue.
```
[FA001] [Microsoft][ODBC Driver 17 for SQL Server]Cannot use Authentication option with Integrated Security option. (0) (SQLDriverConnect); [FA001] [Microsoft][ODBC Driver 17 for SQL Server]Invalid connection string attribute (0)
```

Is there something else I need to do for Azure authentication to work correctly?

**Comment by NZSmartie** [comment]
I've investigated further and there are two things that stod out.
1. An older version of the _ODBC Driver 17 for SQL Server_ was installed that did not support Azure AD Interactive authentication option. 
   - The latest version can be obtained from https://docs.microsoft.com/en-us/sql/connect/odbc/download-odbc-driver-for-sql-server?view=sql-server-ver15
2. (only applies to mssql-django==1.0b1) When no `USER` is provided, `Integrated Security` will be used instead. which was catching me out earlier. I've patched my local install of `mssql-django` to contain the patch https://github.com/microsoft/mssql-django/commit/b41e8b4cd31ce5e3c7e074c4a82e7da303654a54 hopefully an update comes out soon

**Comment by absci** [comment]
Thanks for pointing this out, I have updated the Wiki to recommend people using the latest ODBC 17.
The PyPi release is synced with the `master` branch. If you'd like to try some `dev` branch feathers, you could clone `dev` and run `pip install -e .` in `mssql-django` folder.
