### ISSUE TITLE
Initial Django Migration Error MSSQL-DJANGO 1.4

### ISSUE THREAD

**Issue by xtoller** [microsoft/mssql-django#337]
**Question**

Can anyone help me with this? I'm getting an error message when I was trying to run the initial migration.
cmd: python manage.py makemigrations

Version:
Python: 3.11.7
mssql-django: 1.4
pyodbc: 5.0.1
Django:  5.0.1

Database in Setting.py
DATABASES = {
    'default': {
        'ENGINE': 'mssql',
        'NAME': 'testDB',
        'HOST': con.SQL_SERVER,
        'PORT': con.SQL_HOST,
        'USER': con.SQL_USERNAME,
        'PASSWORD': con.SQL_PASSWORD,
        'Trusted_Connection': 'no',
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server'
        }
    }
}

"C:\Documents\venv\Lib\site-packages\mssql\base.py", line 80, in encode_value
    if ';' in v or v.strip(' ').startswith('{'):
       ^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable

**Comment by mShan0** [comment]
Hi @xtoller, can you provide a full stack trace? 

Also, do you run into the same issue on MSSQL-Django 1.3?

**Comment by quimey** [comment]
I get that error when the password is empty. Did you double check that?

**Comment by mShan0** [comment]
It seems most likely that your password value is empty like quimey mentioned.

**Comment by xtoller** [comment]
Like what quimey mentioned. the password is empty.
Once I confirm I populated all the all required fields, I was able to connect without any issue.

Thank you everyone!!
