### ISSUE TITLE
Greater than in UniqueConstraint not work correctly.

### ISSUE THREAD

**Issue by NovinDeveloper** [microsoft/mssql-django#339]
**Software versions**
* Django: 4.2.9
* mssql-django: 1.4
* python:  3.9.2
* SQL Server: 2019

**Table schema and Model**
```
class TestModel(models.Model):
    Column = models.BigIntegerField()

    class Meta:
        db_table = "TestModel"
        constraints = [
            models.UniqueConstraint(fields=("Column",),
                                    condition=Q(Column__gt=0),
                                    name='column_unique')
        ]
```

**Problem description and steps to reproduce**
When i add a new record (Column=5463254 ) with django orm in TestModel, the generated validate query by mssql is:

```
SELECT
	1 AS [_check] 
WHERE
	COALESCE (
		(
			5463254 > 0 
		AND
		CASE
				
				WHEN EXISTS ( SELECT TOP 1 1 AS [a] FROM [TestModel] U0 WHERE ( U0.[Column] = 5463254 AND U0.[Column] > 0 ) ) THEN
			TRUE ELSE FALSE 
			END = TRUE 
	),
TRUE 
	) = TRUE 
```

**Error message/stack trace**
This query not work in sql server and i get this error when run this query in sql server:

```
Msg 102, Level 15, State 1, Line 6
Incorrect syntax near '>'.
Msg 156, Level 15, State 1, Line 10
Incorrect syntax near the keyword 'THEN'.

```

**Comment by mShan0** [comment]
Hi @NovinDeveloper, does this happen on 1.3?

**Comment by NovinDeveloper** [comment]
Hi @mShan0
Yes, this problem happen in 1.3.
It looks like this problem not happen when i add multi fields in "fields", but i want add only one column to "fields".
```
models.UniqueConstraint(fields=("Column", "Column1"),
                                    condition=Q(Column__gt=0),
                                    name='column_unique')
```

**Comment by mShan0** [comment]
Thanks for the info. Will investigate further

**Comment by dauinsight** [comment]
Hi @NovinDeveloper you can expect a fix for this issue in the next release. Thank you.
