### ISSUE TITLE
Django 5: GeneratedFields not supported by SQL Server?

### ISSUE THREAD

**Issue by martstr** [microsoft/mssql-django#347]
**Question**
I've started experimenting with Django 5.0's GeneratedField. Seeing that mssql-django should support Django 5, and that SQL Server appears to support computed columns, both persisted and not, I had high hopes.

Unfortunately,
"fields.E220: SQL Server does not support GeneratedFields."

The database currently resides on an SQL Server 2017 installation.

Is this supposed to work? (Since I'm not providing any details, I'm more than happy with one-line responses as "Nope, not supported yet" or "Yep, it's supported, you're probably doing something wrong.")

**Comment by mShan0** [comment]
Hi there, the PR adding support for generated fields is merged but not released yet

https://github.com/microsoft/mssql-django/pull/335

**Comment by martstr** [comment]
Perfect, looking forward to it!

Thanks for the swift response.
