### ISSUE TITLE
Migrations not working

### ISSUE THREAD

**Issue by luizfelipevbll** [microsoft/mssql-django#37]
I was using mariadb connection but had to migrate to MSSQL 
So I deleted all migrations folder stuff and remade the migrate, makemigrations... 

First problem I found is that some columns that by default allowed Null values on MySQL now it seens the default is to not allow Null values on SQLSERVER...

The second problem is that altering a table is not working on DB level
I have a table created and lately tried to change and migrate a specif column to **unique=True**, made and applied the migrations but when runing the query directly on a SQL Client the migration did not change the Table structure and I still was able to insert a duplicate value on the column ...
So I had to run directly
 ```sql
ALTER TABLE table ADD UNIQUE (column);
```

**Comment by absci** [comment]
This issue should be fixed in the latest release.
