### ISSUE TITLE
[QUESTION] Why is  supports_ignore_conflicts = False 

### ISSUE THREAD

**Issue by nooha102** [microsoft/mssql-django#376]
**Question**
Why is  supports_ignore_conflicts = False made False over here. https://github.com/microsoft/mssql-django/blob/dev/mssql/features.py#L41

I wanted to use this feature and enabled it in my django application for bulk create and it seems to be working fine. Is there any particular reason it is made false?

**Relevant Issues and Pull Requests**
https://github.com/microsoft/mssql-django/issues/295

**Comment by mShan0** [comment]
Hi @nooha102, It was changed here as MSSQL does not support it:
https://github.com/ESSolutions/django-mssql-backend/issues/10

To double check, we ran our tests with the feature enabled and ran into multiple test failures
