### ISSUE TITLE
Any ETA on stable release?

### ISSUE THREAD

**Issue by tiholic** [microsoft/mssql-django#38]
Firstly, it is great to see that this package is being continued officially. 💯 

I see currently this package is in beta. Do we have any ETA on stable release?

**Comment by absci** [comment]
Thanks for trying out this project. We're currently determining the date for release.

**Comment by aberg-cubist** [comment]
Would it be possible to make a b2 release in the meantime, I would really like to try out the JSONField!

**Comment by absci** [comment]
> Would it be possible to make a b2 release in the meantime, I would really like to try out the JSONField!

If you would like to try the `dev` branch, you could `git clone`, `checkout dev`. Then `pip install -e .` in `mssql-django` folder.

**Comment by rmControls** [comment]
I am also waiting for Django 3.2 supported version... any update on this??

**Comment by absci** [comment]
> I am also waiting for Django 3.2 supported version... any update on this??

I don't have any updates at the moment.

**Comment by absci** [comment]
Good news, PyPi will be updated on June 30, 2021 with version 1.0rc1, and GA release on July 29.

**Comment by WayneLambert** [comment]
Hi @absci, will the GA version at the end of the month include support for Django 3.2 as well? I can see that you have updated the project description on PyPI to reflect that Django 3.1 is supported.

Also, it would be good if the classifiers metadata is also updated with the versions of Python/Django that is supported.

Thanks for taking this project on to improve compatibility with SQL Server.

**Comment by absci** [comment]
> Hi @absci, will the GA version at the end of the month include support for Django 3.2 as well? I can see that you have updated the project description on PyPI to reflect that Django 3.1 is supported.
> 
> Also, it would be good if the classifiers metadata is also updated with the versions of Python/Django that is supported.
> 
> Thanks for taking this project on to improve compatibility with SQL Server.

Thanks for your suggestions, Django 3.2 is currently supported with 1.0rc1 I'll update the readme and classifiers.

**Comment by WayneLambert** [comment]
> Thanks for your suggestions, Django 3.2 is currently supported with 1.0rc1 I'll update the readme and classifiers.

Hi @absci, thanks. I look forward to the GA version being made available.

**Comment by absci** [comment]
GA release completed end of July.
