### ISSUE TITLE
django.db.utils.Error: ('01000', "[01000] [unixODBC][Driver Manager]Can't open lib 'ODBC Driver 17 for SQL Server' : file not found (0) (SQLDriverConnect)")

### ISSUE THREAD

**Issue by zhao-li** [microsoft/mssql-django#39]
Hi,

Thank you for providing an officially supported library to connect Django with SQL Server.

I am running into the following error whenever Django tries to connect to the database:
`django.db.utils.Error: ('01000', "[01000] [unixODBC][Driver Manager]Can't open lib 'ODBC Driver 17 for SQL Server' : file not found (0) (SQLDriverConnect)")`

I've tried to install the ODBC drivers with: `yum install unixODBC-devel`
These are the versions pip has installed:
```
mssql-django 1.0b1
pyodbc 4.0.30
```
These are my Django database settings:
```
DATABASES = {
    'default': {
        'ENGINE': 'mssql',
        'NAME': 'test',
        'USER': 'test',
        'PASSWORD': 'test',
        'HOST': 'database',
        'PORT': '1433',
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
        },
    }
}
```

Please let me know if there's anything else I can provide to help troubleshoot this.  Or if there are any troubleshooting steps that you'd recommend I take, that would be extremely helpful.

Thank you for your time 🙏🏻

In case it's useful here are the really long information:

I'm running this in a container based off of `registry.access.redhat.com/ubi8/python-38`.

All of the libraries and their versions:
```
$ pip list
Package                       Version
----------------------------- ---------
alabaster                     0.7.12
asgiref                       3.3.4
astroid                       2.5.6
Babel                         2.9.1
certifi                       2020.12.5
chardet                       4.0.0
coverage                      5.3.1
Django                        3.1.10
django-cors-headers           3.7.0
djangorestframework           3.12.4
djangorestframework-jsonapi   4.0.0
docutils                      0.17.1
idna                          2.10
imagesize                     1.2.0
inflection                    0.5.1
isort                         5.8.0
Jinja2                        2.11.3
lazy-object-proxy             1.6.0
MarkupSafe                    1.1.1
mccabe                        0.6.1
mssql-django                  1.0b1
packaging                     20.9
pip                           21.1.1
pycodestyle                   2.6.0
Pygments                      2.9.0
pylint                        2.8.2
pylint-django                 2.4.4
pylint-plugin-utils           0.6
pyodbc                        4.0.30
pyparsing                     2.4.7
pytz                          2021.1
PyYAML                        5.3.1
requests                      2.25.1
setuptools                    41.6.0
snowballstemmer               2.1.0
Sphinx                        3.4.3
sphinxcontrib-applehelp       1.0.2
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        1.0.3
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.4
sqlparse                      0.4.1
toml                          0.10.2
unittest-xml-reporting        3.0.4
urllib3                       1.26.4
wrapt                         1.12.1
```

Entire error output:
```
backend_1             | Traceback (most recent call last):
backend_1             |   File "/usr/lib64/python3.8/threading.py", line 932, in _bootstrap_inner
backend_1             |     self.run()
backend_1             |   File "/usr/lib64/python3.8/threading.py", line 870, in run
backend_1             |     self._target(*self._args, **self._kwargs)
backend_1             |   File "/opt/app-root/lib64/python3.8/site-packages/django/utils/autoreload.py", line 53, in wrapper
backend_1             |     fn(*args, **kwargs)
backend_1             |   File "/opt/app-root/lib64/python3.8/site-packages/django/core/management/commands/runserver.py", line 121, in inner_run
backend_1             |     self.check_migrations()
backend_1             |   File "/opt/app-root/lib64/python3.8/site-packages/django/core/management/base.py", line 459, in check_migrations
backend_1             |     executor = MigrationExecutor(connections[DEFAULT_DB_ALIAS])
backend_1             |   File "/opt/app-root/lib64/python3.8/site-packages/django/db/migrations/executor.py", line 18, in __init__
backend_1             |     self.loader = MigrationLoader(self.connection)
backend_1             |   File "/opt/app-root/lib64/python3.8/site-packages/django/db/migrations/loader.py", line 53, in __init__
backend_1             |     self.build_graph()
backend_1             |   File "/opt/app-root/lib64/python3.8/site-packages/django/db/migrations/loader.py", line 216, in build_graph
backend_1             |     self.applied_migrations = recorder.applied_migrations()
backend_1             |   File "/opt/app-root/lib64/python3.8/site-packages/django/db/migrations/recorder.py", line 77, in applied_migrations
backend_1             |     if self.has_table():
backend_1             |   File "/opt/app-root/lib64/python3.8/site-packages/django/db/migrations/recorder.py", line 55, in has_table
backend_1             |     with self.connection.cursor() as cursor:
backend_1             |   File "/opt/app-root/lib64/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
backend_1             |     return func(*args, **kwargs)
backend_1             |   File "/opt/app-root/lib64/python3.8/site-packages/django/db/backends/base/base.py", line 259, in cursor
backend_1             |     return self._cursor()
backend_1             |   File "/opt/app-root/lib64/python3.8/site-packages/mssql/base.py", line 226, in _cursor
backend_1             |     conn = super()._cursor()
backend_1             |   File "/opt/app-root/lib64/python3.8/site-packages/django/db/backends/base/base.py", line 235, in _cursor
backend_1             |     self.ensure_connection()
backend_1             |   File "/opt/app-root/lib64/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
backend_1             |     return func(*args, **kwargs)
backend_1             |   File "/opt/app-root/lib64/python3.8/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
backend_1             |     self.connect()
backend_1             |   File "/opt/app-root/lib64/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
backend_1             |     raise dj_exc_value.with_traceback(traceback) from exc_value
backend_1             |   File "/opt/app-root/lib64/python3.8/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
backend_1             |     self.connect()
backend_1             |   File "/opt/app-root/lib64/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
backend_1             |     return func(*args, **kwargs)
backend_1             |   File "/opt/app-root/lib64/python3.8/site-packages/django/db/backends/base/base.py", line 200, in connect
backend_1             |     self.connection = self.get_new_connection(conn_params)
backend_1             |   File "/opt/app-root/lib64/python3.8/site-packages/mssql/base.py", line 320, in get_new_connection
backend_1             |     conn = Database.connect(connstr,
backend_1             | django.db.utils.Error: ('01000', "[01000] [unixODBC][Driver Manager]Can't open lib 'ODBC Driver 17 for SQL Server' : file not found (0) (SQLDriverConnect)")
```

**Comment by timnyborg** [comment]
Have you installed the ODBC Driver 17 library? https://docs.microsoft.com/en-us/sql/connect/odbc/download-odbc-driver-for-sql-server?view=sql-server-ver15

**Comment by zhao-li** [comment]
> Have you installed the ODBC Driver 17 library? https://docs.microsoft.com/en-us/sql/connect/odbc/download-odbc-driver-for-sql-server?view=sql-server-ver15

I think I did. I issued: `yum install unixODBC-devel`
Is there a way to verify/check/confirm? Or was there another command to install the ODBC drivers?

Thank you for your help 🙏🏻

**Comment by timnyborg** [comment]
unixodbc is a separate requirement, which allows access to any installed drivers.  You need to install the driver itself, the method depending on your distro: https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-ver15

**Comment by vamshikrishnaakula** [comment]
Zhao-li bro am trying to dockerise my django+ sql server the application was docerized succesfully but while doing sql server am getting db.utils 01000 error how do you solved it was

**Comment by zhao-li** [comment]
@vamshikrishnaakula sorry, it's been quite a while since I last touched this.
Without much other information, this is all I can recommend:
- verify the ODBC driver is installed, e.g. `msodbcsqlxx`
- verify if these optional libraries are installed and is helpful: `unixodbc-dev`
- verify if these python libraries are installed: `mssql-django`, `pyodbc`
- check if you missed any steps from here: https://learn.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-ver15

If you share your code, then I can take a look and see if anything jumps out at me.

Good luck 🍀

**Comment by vamshikrishnaakula** [comment]
zhao-li  bro . .  sorry for late reply i didnt see you response  here is my code  you review once  when i ran locally it was worked fine through engine : 'mssql'
the thing is when we come to container only 
i went through that microsoft drivers but i am using windows os eventhough  i didnt get  

Thankyou in advance 

https://github.com/vamshikrishnaakula/django-photoapp/tree/main

**Comment by zhao-li** [comment]
@vamshikrishnaakula No worries; it's all good.  Thanks for sharing the code.

I think the database hostname here: https://github.com/vamshikrishnaakula/django-photoapp/blob/main/DjangoJavaTpointCRUD/settings.py#L107
is pointing to your host machine and not your container.

I would expect the hostname to be the service name defined here: https://github.com/vamshikrishnaakula/django-photoapp/blob/main/docker-compose.yml#L14
or another name defined by the `container_name` configuration: https://docs.docker.com/compose/compose-file/compose-file-v3/#container_name

Hope that helps 🤞 and good luck 🍀

**Comment by vamshikrishnaakula** [comment]
bro tq for your efforts towards me .....here small my  doubt, after corrections  done as of you said no need of installing any drivers like (unixodbc) . . .?

**Comment by zhao-li** [comment]
@vamshikrishnaakula sorry, I assumed you had those in place already.

For the `msodbcsql18` and/or `unixodbc` driver(s), you'll need to perform these steps:
https://learn.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-ver15#ubuntu18
```
curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
curl https://packages.microsoft.com/config/ubuntu/$(lsb_release -rs)/prod.list > /etc/apt/sources.list.d/mssql-release.list
apt-get update
ACCEPT_EULA=Y apt-get install -y msodbcsql18
ACCEPT_EULA=Y apt-get install -y mssql-tools18 # optional: for bcp and sqlcmd
sudo apt-get install -y unixodbc-dev # optional: for unixODBC development headers
```
during your build process, which is determined by your `Dockerfile`: https://github.com/vamshikrishnaakula/django-photoapp/blob/main/docker/python/Dockerfile#L5

To install the `pymssql` Python package, add it to your dependency list:
https://github.com/pymssql/pymssql
```
pip install pymssql
```
in your `requirements.txt`: https://github.com/vamshikrishnaakula/django-photoapp/blob/main/requirements.txt

For additional context, this was a decent documentation: https://www.microsoft.com/en-us/sql-server/developer-get-started/python/ubuntu

Hope that helps 🙏

**Comment by zhao-li** [comment]
@vamshikrishnaakula if you want to learn more about containers:
* this is the project template I use for all of my projects, which are usually containerized: https://github.com/zhao-lin-li/project-template
  * I've tried to incorporate the best practices listed here (as well as lessons learned while using `Docker` and `Docker Compose`: https://docs.docker.com/develop/develop-images/dockerfile_best-practices/
* here's an example project using container and Django (but without MSSQL...sorry): https://gitlab.com/starting-spark/porter/backend

Please feel free to reach out if you want to learn more about containers.

Take care 🌈

**Comment by vamshikrishnaakula** [comment]
tq....brother @zhao-li
