### ISSUE TITLE
[QUESTION]Here are two questions, Can it support python 3.11？and Can it support django async well?

### ISSUE THREAD

**Issue by HeroZ09** [microsoft/mssql-django#398]
**Question**
Can it support python 3.11？or When it can  support python 3.11?

Can it support django async well?

**Comment by mShan0** [comment]
Yes, both are supported. Are you running into problems?

**Comment by HeroZ09** [comment]
> Yes, both are supported. Are you running into problems?

Hi mShan @mShan0 ，thanks for your reply, when I install mssql-django,it looks below:
─ mssql-django is installable and it requires limit python >=3.7,<3.11 
│  └─ python >=3.7,<3.11 , which can be installed;

**Comment by mShan0** [comment]
What version of mssql-django are you trying to install? Where are you installing it from?

**Comment by HeroZ09** [comment]
> What version of mssql-django are you trying to install? Where are you installing it from?

version 1.5， and I use conda  install ，cmd below：
conda install conda-forge::mssql-django
from https://anaconda.org/conda-forge/mssql-django

**Comment by HeroZ09** [comment]
> What version of mssql-django are you trying to install? Where are you installing it from?

@mShan0   I change from conda to pip, and it can support python 3.11~  thanks for your support~
BTW, can you teach me how to modify the "session program"?

**Comment by mShan0** [comment]
We didn't upload our project to Conda ourselves so we haven't been maintaining it on that side so the supported Python versions were never updated. Glad you got it working with Pip.

What exactly do you mean by session program?

**Comment by HeroZ09** [comment]
> We didn't upload our project to Conda ourselves so we haven't been maintaining it on that side so the supported Python versions were never updated. Glad you got it working with Pip.
> 
> What exactly do you mean by session program?
session program 
->  i want to see the program name change to “testapp" on db site (sql: select * from sys.sysprocesses) ，and try setting below:
'OPTIONS': {
               'extra_params': 'APP=testapp',  
           },
@mShan0 Could you please help to double check if the setting is right~~~
thanks very much~

**Comment by mShan0** [comment]
Yes that is correct
