### ISSUE TITLE
Temp Tables for big delete queries don't work for UUIDs

### ISSUE THREAD

**Issue by martinzellner** [microsoft/mssql-django#46]
Hello,

we are stuggeling with the following issue:

I'm running a big delete query with ~ 17000 entries:
`Model.objects.filter(pk__in=delete_list).delete()`

What mssql-django does is to create a temp-table to not exceeed the maximum number of parameters:
`CREATE TABLE #Temp_params (params nvarchar(32))`
`INSERT INTO #Temp_params VALUES ('fe5633e3-5ad9-471a-9046-000364aada58'), `

Unfortunately my primary key is a UUID and hence has 36 characters. Wouldn't it make more sense to create a temp table that has the same datatype as the field to be filtered for?

Thanks in adavance for your help.

**Comment by absci** [comment]
I think it makes sense to have the same data type in the temp table. we'll make some updates in the future.
