### ISSUE TITLE
Replace regex_clr.dll with a non-binary solution that works with SQL Server and Azure SQL DB

### ISSUE THREAD

**Issue by vwarchu** [microsoft/mssql-django#5]
The existing regex solution has a couple issues: it involves a binary in the open source code base which should be avoided, and it does not work on Azure SQL DB due to its reliance on the command sp_configure, which does not exist on Azure SQL DB.

A new implementation for regex_clr may be required to resolve the above issues.

**Comment by absci** [comment]
regex_clr.dll added to PyPi through package_data.
