### ISSUE TITLE
Please, is Always encrypted working in this project? Not sure if it is an unsupported feature.

### ISSUE THREAD

**Issue by manuel-rdco** [microsoft/mssql-django#54]
Hello.

I am trying to use this project with the always encrypted feature and Azure sql. 

A simple select * query is working, but returning encrypted field illegible so, I tried Pyodbc directly in a small program in python, which is working and returning field as clear text. In Django, however, I am using the equivalent parameters and it is returning the field as encrypted, not as clear text as it should. The OPTIONS parameter I am using is :
... 
        'OPTIONS': {
            'driver': "ODBC Driver 17 for SQL Server",
            'extra_params': 'ColumnEncryption=Enabled;KeyStoreAuthentication=KeyVaultClientSecret;KeyStorePrincipalId='+client_id+';KeyStoreSecret='+client_secret+'',
        },
And as I said, the equivalent KeyStoreAuthentication, KeyStorePrincipalId, KeyStoreSecret parameters are working in python with pyodbc.

Thank you very much.

**Comment by manuel-rdco** [comment]
Hello.

I found out that ODBC with **Always Encrypted** is actually working for the "select all" example I was using. I created a cursor and used the connection in this way, for example:
from django.db import connection
c = connection.cursor()
sql = "SELECT * FROM prueba_encriptado;"
c.execute(sql)
print("WORKS: ", c.fetchall())

What is not working as expected is doing **select *** using **manage.py dbshell** directly, which returns fields unencrypted.

So I close the issue I had opened.

Thank you very much, anyway.

**Comment by manuel-rdco** [comment]
I found out that Inserts are working as well with **Always Encrypted**.
Thank you.

**Comment by manuel-rdco** [comment]
as to dbshell behaviour, just in case someone else is having trouble, I can see in https://docs.djangoproject.com/en/3.2/ref/django-admin/ the following:
_Note
Be aware that not all options set in the OPTIONS part of your database configuration in DATABASES are passed to the command-line client, e.g. 'isolation_level'._
So, this appears to be the reason why Always Encrypted is not working as expected in **manage.py dbshell**.

Have a good day. Thank you.

**Comment by absci** [comment]
Glad to hear it worked out for you. We're also running some tests at the moment to verify it.

**Comment by manuel-rdco** [comment]
All right. In order to improve the docs, let me suggest updating README.md if the testing is satisfactory. I searched 'Always encrypted' and presently it does not appear in the documentation. Thank you.

**Comment by manuel-rdco** [comment]
As well as that, I saw In the source code at https://github.com/microsoft/mssql-django/blob/dev/mssql/base.py the following:
_# extra_params are glued on the end of the string without encoding,
..._
So I am sure that many other characteristics working in pyodbc are also present in mssql-django via **extra_params**  (with the correct formatting) and are not documented. It is implicit, but perhaps something could be said just to clarify.

Thank you very much.

**Comment by vwarchu** [comment]
We should revisit this in terms of appropriate documentation

**Comment by jmah8** [comment]
Added Always Encrypted documentation to the [wiki](https://github.com/microsoft/mssql-django/wiki/Always-Encrypted).
