### ISSUE TITLE
How to specify schema?

### ISSUE THREAD

**Issue by fnea** [microsoft/mssql-django#56]
Is there a way to specify a schema other than the default?  If so, could there be one?

I know there are ways for Django with a Postgres backend, but it doesn't look like it for MSSQL.

Thanks.

**Comment by absci** [comment]
Hi, are you trying to use a specific schema for a model?
In your `models.py`. You could have db_table in class Meta. 
```
class myModel(models.Model):
...
    class Meta:
        db_table = "[schema].[table]"
```

**Comment by theultimate1** [comment]
What if you want to specify schema for the inspectdb command?

**Comment by absci** [comment]
> What if you want to specify schema for the inspectdb command?

1. Change the default schema for `your_user` to match the schema you'd like to inspectdb.
2. Make sure `your_user` has the privilege to access it. (`your_user` should not be in `sysadmin` group, if so default schema will be ignored)

For example:
```
ALTER USER [your_user] WITH DEFAULT_SCHEMA=[your_schema]
GO
ALTER AUTHORIZATION ON SCHEMA::your_schema TO [your_user]
GO
```

**Comment by yazdan** [comment]
@absci thanks for your answer

I have multiple schemas in DB and want to use `inspectdb ` to generate model.

Is there any way to easily do that?

I've reviewed `introspection.py ` file and found out there is couple of place that it calls `SCHEMA_ID()` and I think changing this is the starting point

**Comment by absci** [comment]
> @absci thanks for your answer
> 
> I have multiple schemas in DB and want to use `inspectdb ` to generate model.
> 
> Is there any way to easily do that?
> 
> I've reviewed `introspection.py ` file and found out there is couple of place that it calls `SCHEMA_ID()` and I think changing this is the starting point

Yes, you're right, I think that `SCHEMA_ID()` does limited `inspectdb` to only generate models for the default schema.

**Comment by RaynoKriel** [comment]
> Yes, you're right, I think that `SCHEMA_ID()` does limited `inspectdb` to only generate models for the default schema. I'll try to change that in the future.
> 
> `--schema` flag added to specify the schema. `python manage.py inspectdb --schema "your_schema"`
This is awesome, would you just call the flag the same way as --database (as it currently still tells me it is not recognized)
sorry if this a stupid question ><

**Comment by absci** [comment]
> 

Currently we haven't published a new release yet. So to try it, you have to install from the source. And don't forget to add `mssql` to `INSTALLED_APPS`.

**Comment by OdifYltsaeb** [comment]
Thank you @absci ! I just found out I need this exact thing too. Thank you again!

**Comment by OdifYltsaeb** [comment]
I have another schema related case to fix - now that we can specify a schema for inspectdb. How can I specify a different schema for different databases? Each client has their own database and the schema name might be different from database to database.

Can I specify schema per database connection somehow? something like this perhaps: https://stackoverflow.com/questions/50819748/django-and-postgresql-schemas, https://code.djangoproject.com/ticket/28774

**Comment by OdifYltsaeb** [comment]
Allright, thanks. If there's no other way then I'll go with this one. Thank you again!

**Comment by OdifYltsaeb** [comment]
I've tested it some now and things are far from perfect, unfortunately.

For example - I have included models in two different files and added their schema prefixes to their db_table configuration.

Then this happens:
```
In [1]: from datastore.trk_models import MyModelName
In [2]: MyModelName.objects.using('specialDB').first()
ProgrammingError: ('42S02', "[42S02] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid object name 'trk.my_model_name'. (208) (SQLExecDirectW)")
```

where `trk` is the schema name.
Yet when I do this: 
```
a = MyModelName.objects.raw('SELECT * from trk.my_model_name').using('specialDB')
```

then I can loop over the selected items just fine. 

Another problem is that having the same model names defined in different model files - for having different schemas, does not seem to work well either.  It results in a different error:

```
from datastore.flexport_models import MyModelName
RuntimeError: Conflicting 'eventlogger' models in application 'datastore': <class 'datastore.trk_models.Eventlogger'> and <class 'datastore.flexport_models.Eventlogger'>.
```
Which would make me name the models too per each schema... which makes handling all this very awkward.

Alan

**Comment by tspanos** [comment]
There seems to be a bug when a specified schema contains a table name that also exists in the default schema. Instead of extracting the column names from the specified schema, inspectdb extracts the columns from the default schema. The issue stems from the function that retrieves the table description as it does not specify the schema when requesting the table's columns. 

    def get_table_description(self, cursor, table_name, identity_check=True):
        """Returns a description of the table, with DB-API cursor.description interface

        # map pyodbc's cursor.columns to db-api cursor description
        columns = [[c[3], c[4], None, c[6], c[6], c[8], c[10], c[12]] for c in cursor.columns(table=table_name)]

This is how I fixed it.

    def get_table_description(self, cursor, table_name, identity_check=True):
        """Returns a description of the table, with DB-API cursor.description interface.

        # map pyodbc's cursor.columns to db-api cursor description
        schema = get_schema_name().replace("'", "").replace("\\", "")
        columns = [[c[3], c[4], None, c[6], c[6], c[8], c[10], c[12]] for c in cursor.columns(table=table_name, 
                                                                                              schema=schema)]

**Comment by root4417** [comment]
Change the default schema for your_user to match the schema you'd like to inspectdb.
Make sure your_user has the privilege to access it. (your_user should not be in sysadmin group, if so default schema will be ignored)
For example:

ALTER USER [your_user] WITH DEFAULT_SCHEMA=[your_schema]
GO
ALTER AUTHORIZATION ON SCHEMA::your_schema TO [your_user]
GO

Really Useful suggestion: 
(your_user should not be in sysadmin group, if so default schema will be ignored)


I spent hours on this and this saved my life. Thanks

**Comment by ismaina** [comment]
> Is there a way where we can specify a schema in the DB config in settings.py? If we're using PostgreSQL then in the DB config itself we can define the schema like below.
> 
> ```
>     'OPTIONS': {
>         'options': '-c search_path=django,public'
>     },
> ```
> 
> Is there a way we can do this mssql-django? Because I want to define schemas for the tables that are created by Django (ex: django_session, django_auth etc) with `db_table='[schema].[table]'` approach we cannot specify the scheamas for tables that are created by django or any 3rd party libraries.

This worked for me

**Comment by RzNmKX** [comment]
Still would be nice to be able to specify schema. Example is: company with large, legacy MSSQL databases. Small team working on new django app - default database will be new and specific to the app. Everything else is on the large databases that's segregated by schemas. We do not have ability to modify user account.

**Comment by Wedge009** [comment]
> `--schema` flag added to specify the schema. `python manage.py inspectdb --schema "your_schema"`

Was this actually implemented (or has something broken since implementation)? I see mention of this in the release notes for mssql-django 1.1, I'm using mssql-django 1.5 with django 5.0.8, yet when I try `python manage.py inspectdb --schema "schema_name"` I get the following:

```
usage: manage.py inspectdb [-h] [--database DATABASE] [--include-partitions] [--include-views] [--version] [-v {0,1,2,3}] [--settings SETTINGS] [--pythonpath PYTHONPATH] [--traceback] [--no-color]
                           [--force-color]
                           [table ...]
manage.py inspectdb: error: unrecognized arguments: --schema
```

**Comment by FranciscoNC** [comment]
> What if you want to specify schema for the inspectdb command?

I had this problem too, I read mssql/introspection.py and I saw this:

```

def get_schema_name():
    return getattr(settings, 'SCHEMA_TO_INSPECT', 'SCHEMA_NAME()')

```
I only have to set this setting before run inspectdb
