### ISSUE TITLE
Azure SQL version/features not checked correctly

### ISSUE THREAD

**Issue by AdamosX** [microsoft/mssql-django#60]
Our app uses Azure SQL as database. We encountered a problem while trying to use JSON field and found out that it is supported by Azure SQL but the check is not implemented correctly.
https://github.com/microsoft/mssql-django/blob/5007a268dbf8bdc3ad6c98c36a0059295d61d181/mssql/features.py#L78

It seems that SQL Server and Azure SQL have different version numbers.
```sql
SELECT CAST(SERVERPROPERTY('ProductVersion') AS varchar)
```
reports 12 on Azure but in reality it supports more features.
https://github.com/microsoft/mssql-django/blob/5007a268dbf8bdc3ad6c98c36a0059295d61d181/mssql/base.py#L404

There seems to be code that handles version checks for Azure SQL
https://github.com/microsoft/mssql-django/blob/5007a268dbf8bdc3ad6c98c36a0059295d61d181/mssql/base.py#L424
but it's not used correctly when declaring features.

**Comment by absci** [comment]
Thanks for report this, I'll look into it.

**Comment by looser990** [comment]
@absci where can we check release roadmap for this project as we have same issue so we kinda need to decide if we are going to use JSON field or not :(

**Comment by vwarchu** [comment]
@looser990 - Thanks for the feedback, we have now added a wiki page for this Github project for "Upcoming Release Notes". This page will preview what will be going in to the next preview or GA release. We don't have a publicly available roadmap of sorts at this time. Hopefully this fits your purpose.
