### ISSUE TITLE
./manage.py test fails with using Azure SQL and Service Principal authentication

### ISSUE THREAD

**Issue by jlaundry** [microsoft/mssql-django#61]
Background:

- I'm using Django==3.1.13, and mssql-django==1.0
- I have created Azure SQL Server, using Service Principal authentication, with two databases: **[db]** and **[test_db]**
- the Service Principal has been configured with db_owner on both databases (i.e., `CREATE USER [app] FROM EXTERNAL PROVIDER; EXEC sp_addrolemember 'db_owner', [app];`)
- I have updated DATABASES in settings.py with `Authentication=ActiveDirectoryServicePrincipal`

I can use Django with no issues.

However, when I run `./manage.py test --keepdb`, I get the following error:

`pyodbc.InterfaceError: ('28000', "[28000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Login failed for user '<token-identified principal>'. (18456) (SQLDriverConnect)")`

This is because the test runner first connects to **[dbo].[master]**, verifies **[test_db]** exists, and then reconnects to **[test_db]**. However, by default Service Principals do not have permission to access **[dbo].[master]** (and ideally shouldn't, when using the same server for multiple applications).

This appears to be an intentional design decision to try connecting without the DB name even when using keepdb, as per [django/db/backends/base/creation.py:52-57](https://github.com/django/django/blob/main/django/db/backends/base/creation.py#L57):

```python
        # We could skip this call if keepdb is True, but we instead
        # give it the keepdb param. This is to handle the case
        # where the test DB doesn't exist, in which case we need to
        # create it, then just not destroy it. If we instead skip
        # this, we will get an exception.
        self._create_test_db(verbosity, autoclobber, keepdb)
```

If I comment out this line, it works without issue.

I've raised this as a Django bug [#33009](https://code.djangoproject.com/ticket/33009#ticket), but this may be rejected as the mssql backend could instead override `_create_test_db()` or `create_test_db()` to provide a more specific check (like SQLite does, for example).

**Comment by absci** [comment]
Hi, I see you already did some investigation on this, would you like to provide a patch? Maybe a try block to avoid the permission issue.

**Comment by jlaundry** [comment]
Hi @absci, sorry for going quiet, I've just raised a PR 😊

**Comment by absci** [comment]
Merged, thanks for your contribution.
