### ISSUE TITLE
'mssql' isn't an available database backend

### ISSUE THREAD

**Issue by knickfan7** [microsoft/mssql-django#63]
Hi, I created a new project and installed django, pyodbc and mssql-django and used the example string that was provided. but I am receiving the 'django.core.exceptions.ImproperlyConfigured: 'mssql' isn't an available database backend.

**Comment by abrunner73** [comment]
Hello @knickfan7 I have the same error as you.  Did you figure out what was causing it?  I am having this error when running on Apache24.  Here are the python module versions I am using.  Any advice would be appreciated.

alabaster==0.7.12
asgiref==3.4.1
Babel==2.7.0
certifi==2019.11.28
chardet==3.0.4
colorama==0.4.3
Django==3.2.9
django-debug-toolbar==3.2.2
django-mssql-backend==2.8.1
docutils==0.15.2
entrypoints==0.3
flake8==4.0.1
idna==2.8
imagesize==1.1.0
Jinja2==2.10.3
ldap3==2.9.1
MarkupSafe==1.1.1
mccabe==0.6.1
mod-wsgi==4.9.0
packaging==19.2
pyasn1==0.4.8
pycodestyle==2.8.0
pyflakes==2.4.0
Pygments==2.5.2
pyodbc==4.0.26
pyparsing==2.4.5
pytz==2021.3
requests==2.22.0
six==1.13.0
snowballstemmer==2.0.0
Sphinx==4.3.0
sphinxcontrib-applehelp==1.0.1
sphinxcontrib-devhelp==1.0.1
sphinxcontrib-htmlhelp==2.0.0
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.2
sphinxcontrib-serializinghtml==1.1.5
sqlparse==0.4.2
urllib3==1.25.7

**Comment by wgordon17** [comment]
@knickfan7 What did you do to resolve this?

**Comment by Hakio89** [comment]
[knickfan7](https://github.com/knickfan7) What was the solution ?
