### ISSUE TITLE
Managed Service Identity - Azure Authentication

### ISSUE THREAD

**Issue by shakthifuture** [microsoft/mssql-django#64]
I have enabled **MSI**(Managed Service Identity) in my Azure Database, so I couldn't able to use the **username** and **password** to access the database. How could I connect the azure database using this package?

**More details about what is MSI**: https://techcommunity.microsoft.com/t5/azure-database-support-blog/using-managed-service-identity-msi-to-authenticate-on-azure-sql/ba-p/1288248

Any help would be appreciated.

**Comment by absci** [comment]
Hi, MSI is currently not supported, we'll work on adding that in the future.

**Comment by shakthifuture** [comment]
Hi @absci , Thanks for considering this in the future release. May I know the deadline? because of this restriction, we planning to some other database.

**Comment by vwarchu** [comment]
@shakthifuture - We will do further investigation this month in order to determine estimates and potential timelines. However, we can't commit to an outcome as of yet. We'll provide an update here by end of month.

**Comment by absci** [comment]
Hi, I have added support for MSI in the `dev` branch. 

Simply add `"extra_params": "Authentication=ActiveDirectoryMsi",` to options. For example, https://github.com/microsoft/mssql-django/wiki/Azure-AD-Authentication#activedirectorymsi

**Comment by viklele-webisdom** [comment]
Hi absci,

I am working with @shakthifuture in his project.

Thanks for the quick resolution of the issue. When is it scheduled to become part of the formal release?

Thanks.
Vikram

**Comment by absci** [comment]
> Hi absci,
> 
> I am working with @shakthifuture in his project.
> 
> Thanks for the quick resolution of the issue. When is it scheduled to become part of the formal release?
> 
> Thanks. Vikram

Hi, Next preview release is planned for the end of October.
