### ISSUE TITLE
Package doesn't report error correctly if Email service credentials are wrong

### ISSUE THREAD

**Issue by adolotovs** [microsoft/mssql-django#65]
### Problem
The gmail user account that I was using to send email was subsequently blocked, which caused confusing error message

On db record creation I trigger a signal to "send.mail()", which adds entry to post_office_email table without problems.
However when I run "python manage.py send_queued_mail", it throws the following error:

**_pyodbc.ProgrammingError: ('42000', '[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]At least one of the result expressions in a CASE specification must be an expression other than the NULL constant. (8133) (SQLExecDirectW)')_**

which happens at: **"/usr/local/lib/python3.9/site-packages/post_office/mail.py", line 308, in _send_bulk**

### Cause
I tracked down an issue to see what happens. If Email service credentials are not set correctly or account is blocked, package reports error inside failed_emails list as follows:

**the print of failed_emails at line 295:**
[(<Email: ['test@gmail.com']>, SMTPAuthenticationError(535, b'5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials k12sm1104861edq.59 - gsmtp')), (<Email: ['test@gmail.com']>, SMTPAuthenticationError(535, b'5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials a15sm1279576edr.2 - gsmtp'))]
preee emails [<Email: ['test@gmail.com']>, <Email: ['test@gmail.com']>]

which then subsequently causes above error at line 308: 
**Email.objects.bulk_update(emails_failed,["status","scheduled_time","number_of_retries"])**,

### Setup
Django==3.2.4
django-environ-2==2.1.0
djangorestframework==3.12.4
pyodbc==4.0.32
django-mysql==4.0.0
mssql-django==1.0.0
celery==5.1.2
redis==3.5.3
django-post_office==3.5.3

Kind regards

**Comment by absci** [comment]
Hi, thanks for report this issue. I think it's related `bulk_update multiple fields to null. It's a known limitation currently, we'll patch it in the future.

**Comment by absci** [comment]
I have patched Django's bulk_update in the dev branch https://github.com/microsoft/mssql-django/commit/9c63da9ef1d41b92c3d797522ac5ddef3bf03ceb.
