### ISSUE TITLE
Unable to inspect table - missing 1 required positional argument: 'collation'

### ISSUE THREAD

**Issue by arnists** [microsoft/mssql-django#68]
I managed to fix it by hotfixing the following line: https://github.com/microsoft/mssql-django/blob/dev/mssql/introspection.py#L115

I just hardcoded the collation and then everything worked.

**Comment by absci** [comment]
Could you run `pip freeze` to show what's the environment looks like?

**Comment by arnists** [comment]
```asgiref==3.4.1
backcall==0.2.0
decorator==5.1.0
Django==3.2.7
django-mssql-backend==2.8.1
flake8==3.9.2
importlib-metadata==4.8.1
ipython==7.16.1
ipython-genutils==0.2.0
jedi==0.18.0
mccabe==0.6.1
parso==0.8.2
pep8==1.7.1
pexpect==4.8.0
pickleshare==0.7.5
pkg_resources==0.0.0
prompt-toolkit==3.0.20
ptyprocess==0.7.0
pycodestyle==2.7.0
pyflakes==2.3.1
Pygments==2.10.0
pyodbc==4.0.32
pytz==2021.1
six==1.16.0
sqlparse==0.4.2
traitlets==4.3.3
typing-extensions==3.10.0.2
wcwidth==0.2.5
zipp==3.5.0
```

**Comment by arnists** [comment]
I might add that the SQL executed is a bit restrictive. Making the determination that TABLE_SCHEMA == SCHEMA_NAME makes assumptions that in my case threw out a lot of relevant tables. It's easy enough to fix by just monkeypatching but perhaps there should be a flag for it.

**Comment by absci** [comment]
Seems you're not using this backend, try uninstall `django-mssql-backend` then `pip install mssql-django`. 


> I might add that the SQL executed is a bit restrictive. Making the determination that TABLE_SCHEMA == SCHEMA_NAME makes assumptions that in my case threw out a lot of relevant tables. It's easy enough to fix by just monkeypatching but perhaps there should be a flag for it.

Yes, there're some improvements can be done for inspectdb.

**Comment by absci** [comment]
I have added a `--schema` flag to inspectdb for specify the schema in `dev`  `e702c03`. 

`python manage.py inspectdb --schema "your_schema"`
