### ISSUE TITLE
Unable to generate constraints when schema is specified in a model

### ISSUE THREAD

**Issue by MNielsenViteco** [microsoft/mssql-django#69]
Hello,

We have an implementation where schemas are specified for most of our models. But when making a constraint to any model where the schema is specified, an error is returned because of a naming issue. 
The specific error is this:
django.db.utils.ProgrammingError: ('42000', "[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Incorrect syntax near '.'. (102) (SQLExecDirectW)")
and the cause seems to be that (for db_table = "[vmd].[vmd_virtual_column]") creates an SQL which looks like this:
ALTER TABLE [vmd].[vmd_virtual_column] ADD CONSTRAINT [[vmd].[vmd_virtual_column]_virtual_table_id_1400873a_fk_[vmd].[vmd_virtual_table]_id] FOREIGN KEY ([virtual_table_id]) REFERENCES [vmd].[vmd_virtual_table] ([id]) ()
which is invalid constraint naming in SQL Server.  This has also been attempted with table naming db_table = "vmd].[vmd_virtual_column" which results in
ALTER TABLE [vmd].[vmd_virtual_column] ADD CONSTRAINT [vmd].[vmd_virtual_column_virtual_table_id_1400873a_fk_[vmd].[vmd_virtual_table]_id]].[vmd_virtual_column] FOREIGN KEY ([virtual_table_id]) REFERENCES [vmd].[vmd_virtual_table] ([id]) ()
which is also incorrect.

We have implemented a temporary solution, which currently works with db_table = "[...].[...]" way of writing but not with "...].[...", by overriding the quote_name function in schema.py with
def quote_name(self, name):
        initial_re = re.sub(r'\[\[[a-z]+\]\.\[', '[',self.connection.ops.quote_name(name).replace(']_', '_'))
        return re.sub(r'_\[[a-z]+\]\.', '_',initial_re)
which simply removes the offending parts of the name string. But a better, and more permanent, fix to this would be preferred.

Regards
Mathias Nielsen

**Comment by absci** [comment]
I can reproduce this issue. In my test, when I specify a name to `db_table`, the schema is still `dbo`. I think your table is `[dbo].[vmd].[vmd_virtual_column]`. Could you run `select schema_name(schema_id) as [schema], name from sys.tables` to confirm?

**Comment by absci** [comment]
I have fixed this in dev `7c46275` a few weeks ago, it just replaced the invalid part in _create_index_name.
