### ISSUE TITLE
Bad performance on Azure SQL Database

### ISSUE THREAD

**Issue by Nevin1901** [microsoft/mssql-django#72]
Hi, I tried using this library with a Basic 5 DTU Azure SQL Server and I'm having to wait over 5 seconds for a simple query to go through.

I read somewhere that the horrible performance was caused by the database collation being SQL_Latin1_General_CP1_CI_AS, but I'm not sure if that really is the problem.

I'm not sure if anyone else has this problem, but any help is appreciated.

**Comment by absci** [comment]
I tested with 5 (Basic) DTUs, 2GB Data max size, haven't experienced a similar performance issue. Are there any other applications that also connect to this database?

**Comment by Nevin1901** [comment]
Not any. The database is fast when using it though Azure Data studio, but any database adapter which I tried seemed to be extremely slow.

**Comment by absci** [comment]
Does the connection still slow if you use `sqlcmd`?

**Comment by cgallard01** [comment]
I had the same issue with an enterprise hosted mssql DB with a collation "SQL_Latin1_General_CP1_CI_AS".
It was only fixed by using this approach : 

http://nightlyclosures.com/2019/12/06/fixing-my-dead-slow-sql-server-pyodbc-query-performance-2/

Tested with the last 1.1 release tag

**Comment by absci** [comment]
Looks like it's a pyODBC design to use unicode by default. I could add a variable to `settings.py`, and let people change `connection.setdecoding`, `connection.setencoding` without overriding DatabaseWrapper.

**Comment by ahibrahimm** [comment]
@absci I'm still facing bad performance when connecting to an Azure SQL Server instance but connecting to a local instance makes the performance fast. I tried changing the encoding/decoding to match the db collation, but no luck. Any other options you'd recommend me trying?

I can open a separate issue but thought to ask here first.
