### ISSUE TITLE
Collation issue with #Temp_params table

### ISSUE THREAD

**Issue by vidklopcic** [microsoft/mssql-django#73]
If the column uses a different COLLATION than instance default, a query using this temp table will raise `django.db.utils.ProgrammingError` due to COLLATION conflict. Is there any way to circumvent this issue without changing SQL Server instance defaults?

https://github.com/microsoft/mssql-django/blob/9c63da9ef1d41b92c3d797522ac5ddef3bf03ceb/mssql/functions.py#L141

EDIT: I checked and the DB collation is set correctly (CS), but created #Temp_params table seems to use SQL Instance defaults (CI), which seems quite strange to me. Let me know if you need any other configuration information.

**Comment by absci** [comment]
I'll investigate this, maybe adding `COLLATE DATABASE_DEFAULT` when creating the temp table would fix the issue.
