### ISSUE TITLE
bulk_update not working with None value got ProgrammingError: ('42000', '[42000] [Microsoft][ODBC Driver 17 for SQL Server]

### ISSUE THREAD

**Issue by Imran-Hossain-Saimun** [microsoft/mssql-django#79]
# Entry is a demo model, my model is similar to this

 objs = [
   Entry.objects.get(item_id=5),
]
objs[0].headline = None  // any type field set the value None
Entry.objects.bulk_update(objs, ['headline']) 
# bulk update got error

"ProgrammingError: ('42000', '[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]At least one of the result expressions in a CASE specification must be an expression other than the NULL constant. (8133) (SQLExecDirectW); [42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Statement(s) could not be prepared. (8180)')"

**Comment by absci** [comment]
This issue should be fixed, please upgrade to the latest version of `mssql-django` (1.1.1). 

To explain, basically SQL Server does not allow `CASE ... THEN NULL ... ELSE NULL`. 
In the latest version, bulk_update takes an optional default value, this value will be used for ELSE. 
bulk_update to None value will become `CASE ... THEN NULL ... ELSE 0`. You could also change this value with bulk_update(... default=).
