### ISSUE TITLE
Hierarchyid field type not supported.

### ISSUE THREAD

**Issue by cdgipson** [microsoft/mssql-django#80]
The hierarchyid field type is not supported.  Please add support for this field type.  If there are any known work-arounds that could get my project moving forward that would be great as well.

**Comment by absci** [comment]
I don't think Django has a field type to match the `hierarchyid`, maybe a JSONField would be an alternative? If it's not possible to migrate data to JSON, I think you probably have to work with raw queries to manage the data.

**Comment by cdgipson** [comment]
Correct.  I found a work around for this.  I added an additional varchar field on the database and exposed this new field instead of the hierarchyid field.  I then set triggers on insert and update to update the content of the hierarchyid field with that of the varchar field.
