### ISSUE TITLE
BUG KeyTransformExact applied universally for all database drivers

### ISSUE THREAD

**Issue by jchang10** [microsoft/mssql-django#82]
https://github.com/microsoft/mssql-django/blob/9f58a0056f512ba47126221b16a5c88adc6673f8/mssql/functions.py#L277-L280

This line can't be right?! This applies to all other database drivers (such as mysql, postgresql, etc) by overriding the django.db.model files.

This should get an immediate fix. Did someone copy/paste this wrong here? Should it be this?

    KeyTransformExact.as_microsoft = json_KeyTransformExact_process_rhs

**Comment by absci** [comment]
Thanks for your report, I'll fix this.
