### ISSUE TITLE
Filtered Index referencing many fields prevents changing nullability of indexed foreign key to null

### ISSUE THREAD

**Issue by jean-frenette-optel** [microsoft/mssql-django#90]
Given these Django models where a **Question** may have many **Choices** :

```
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE, null=False)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
```

The resulting migration of **choice** table is like so (question_id FK is not nullable as expected, with a corresponding index correctly created) :

![image](https://user-images.githubusercontent.com/95249592/150595343-a080a628-fc9a-4c3d-bec4-6551d6d20a1f.png)

Now, applying this change (changing the nullability of the question in the choice model to **True**):
`question = models.ForeignKey(Question, on_delete=models.CASCADE, null=True)`

The migration gives the correct result (question_id FK is not nullable as expected):

![image](https://user-images.githubusercontent.com/95249592/150596006-48ce3776-9f8d-4935-a110-9b2bdff3cefb.png)

### The Problem
When a filtered index is referencing the foreign key we want to change to Nullable, the migration gives an error, since the drop index is not generated by the migration.

Applying this **unique_together** class Meta to the Choice model, and making the question back to a **not nullable** value will give the **expected** following result in the database after applying the migration:

![image](https://user-images.githubusercontent.com/95249592/150597548-bf298848-e2b3-4a59-88ec-00e4aa385068.png)

Now, changing the nullability to nullable while keeping the unique_together index definition:
`question = models.ForeignKey(Question, on_delete=models.CASCADE, null=True)` 
will give this error while applying the migration:

`The index 'polls_choice_choice_text_question_id_5992780a_uniq' is dependent on column 'question_id'. (5074) (SQLExecDirectW); [42000] [Microsoft][ODBC Driver 17 
for SQL Server][SQL Server]ALTER TABLE ALTER COLUMN question_id failed because one or more objects access this column. `

This error is normal, since **the mssql-django driver is not generating the required drop and recreate of the filtered index**.

I found in the code, that the indexes and constraints drop is done only when the nullability of the foreign key is changed **in one direction only, here, from nullable to not-nullable**:

![image](https://user-images.githubusercontent.com/95249592/150599021-3653eb2d-f590-452e-b57d-fd4606458277.png)

And, the indexes and contraints re-creation is also done **in one direction only, here, from nullable to not-nullable**:

![image](https://user-images.githubusercontent.com/95249592/150599465-cd413bc5-89d4-47ac-93d8-793e36bec706.png)

### The Solution (?)
By changing the conditions on which the indexes are drop and created back, it works.  I can change the nullability from not-null to null for the foreign key, even if the foreign key is referenced in the index.  After the migration the index is correctly created with the filters.

![image](https://user-images.githubusercontent.com/95249592/150600248-0115c155-82b5-4726-914f-a64f20f0d1a0.png)

and :

![image](https://user-images.githubusercontent.com/95249592/150600376-9fc9e485-2db4-48ed-9fc4-c8f7aadd2cbe.png)

Does it make sense?

Thank you !

**Comment by absci** [comment]
I can reproduce this issue, I think you're right, it's only working one direction currently. Your solution looks good to me, it would be better if you could also add a unit test. Would you like to make a pull request?

**Comment by aemhca** [comment]
We had the same issue thanks for solving this :)
