### ISSUE TITLE
consider implementing can_return_ids_from_bulk_insert feature

### ISSUE THREAD

**Issue by adhamselman** [microsoft/mssql-django#94]
https://docs.microsoft.com/en-us/sql/t-sql/queries/output-clause-transact-sql?view=sql-server-ver15

**Comment by absci** [comment]
Thank you for the feature request, we will review it.

**Comment by jean-frenette-optel** [comment]
Hi, I just submitted this Draft PR for this issue :
https://github.com/microsoft/mssql-django/pull/107
