### ISSUE TITLE
Using azure cli token for authentication

### ISSUE THREAD

**Issue by pettermk** [microsoft/mssql-django#99]
Hi,

In relation with the MSI support that was recently introduced, I want to suggest an enhancement which we have been testing a bit. For seamless switching between local development and production environments, it would be useful if a developer could use the typical azure cli credential flow to authenticate with the database. So, when running in production it would check the managed service identity endpoint for the token, but locally we would pass a token to the mssql-django config and it would pass it on as required.

I had coded up a rudimentary version over at https://github.com/equinor/mssql-django/commit/fbb044107800f7027f18c22bb7fbc18e01def682, but not really keen on maintaining a fork I wanted to check if something like this fits with your plans for the project. If interested, I can clean it up a bit and make a PR. Or please let me know if there is another way it could be achieved.

BR, Petter

**Comment by absci** [comment]
Sure, it sounds good, feel free to make a pull request.
